import { fetchWithAuth } from '../api';

export interface AttendanceRecord {
  id: string;
  date: string;
  classId: string;
  className: string;
  classType?: string;
  time?: string;
  room?: string;
  status: 'present' | 'absent';
  notes?: string;
  isAutoGenerated?: boolean;
  createdAt?: string;
  subjectId?: string;
}

export const attendanceService = {
  async getAll(): Promise<AttendanceRecord[]> {
    const response = await fetchWithAuth('/attendance/records');
    if (response.ok) {
      const data = await response.json();
      return data.data || [];
    }
    return [];
  },

  async save(records: AttendanceRecord[]): Promise<void> {
    await fetchWithAuth('/attendance/records', {
      method: 'POST',
      body: JSON.stringify({ records })
    });
  }
};
