"use client"

import { useState, useEffect } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { toast } from "@/components/ui/use-toast"
import { Button } from "@/components/ui/button"
import { LoadingButton } from "@/components/ui/loading-button"
import { 
  showSuccessNotification,
  showErrorNotification,
  showInfoNotification,
  showWarningNotification
} from "@/components/ui/notification-popup"
import { saveToLocalStorage, getFromLocalStorage } from "@/lib/storage-utils"
import { Input } from "@/components/ui/input"
import { Calendar } from "@/components/ui/calendar"
import { Textarea } from "@/components/ui/textarea"
import { format, isToday, isSameDay, isBefore, startOfDay, addDays } from "date-fns"
import { cn } from "@/lib/utils"
import { useAuth } from "@/lib/auth-context"
// Alternative: Use the attendance service
// import { attendanceService } from "@/lib/services"
import { CalendarIcon, Check, X, Plus, BookOpen, ClipboardCheck, Calendar as CalendarIcon2, Map, Clock, CheckCircle, XCircle, Bell } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { generateAutoPresentRecords } from "@/lib/attendance-utils"
import { 
  sendEmail, 
  sendAttendanceReminder, 
  sendLowAttendanceAlert, 
  sendDailySummary,
  saveEmailPreferences 
} from "@/lib/email-utils"

interface Subject {
  id: string;
  name: string;
  code?: string;
  day?: string; // Day of week
}

interface ClassEntry {
  id: string;
  day: string;
  name?: string;  // Make name optional since we might use subject instead
  subject?: string; // Add subject field for compatibility with settings-schedule-uploader
  time?: string;    // Original format "09:00 - 10:30"
  startTime?: string; // Alternative format: separate start and end times
  endTime?: string;   // Alternative format: separate start and end times
  room: string;
  fromPdf?: boolean;
  classType?: string;
}

// TODO: Refactor type definitions for attendance records
// There's a typing issue related to Record<string, any> usage
// A proper type system should be established for attendance records
// and applied consistently throughout the application
// Current implementation uses any types in some places to maintain compatibility

import { attendanceService, type AttendanceRecord as ServiceAttendanceRecord } from "@/lib/services/attendance-service"

// Use the service type
type AttendanceRecord = ServiceAttendanceRecord;

// Add new interface for holiday data
interface Holiday {
  date: string;
  reason: string;
}

// Add a helper function to filter out break-type classes
const filterNonBreakClasses = (classes: ClassEntry[]): ClassEntry[] => {
  return classes.filter(item => !item.classType || !item.classType.toLowerCase().includes('break'));
};

// Helper function to update the existingRecords state
const updateExistingRecordsState = (classes: ClassEntry[], status: "present" | "absent"): Record<string, any> => {
  const records: Record<string, any> = {};
  classes.forEach(classEntry => {
    const className = classEntry.name || classEntry.subject || "Unknown Class";
    records[classEntry.id] = { 
      id: `${new Date().toISOString().split('T')[0]}-${classEntry.id}`,
      date: new Date().toISOString().split('T')[0],
      classId: classEntry.id,
      className: className,
      status, 
      notes: status === "absent" ? "Marked absent for entire day" : "Marked present for entire day",
      isAutoGenerated: false
    };
  });
  return records;
};

// Add notification helper function
const sendNotification = async (title: string, body: string) => {
  // Check if browser notifications are supported
  if (!("Notification" in window)) {
    console.log("This browser does not support notifications");
    return;
  }
  
  // Check if permission is already granted
  if (Notification.permission === "granted") {
    new Notification(title, { body });
  } 
  // Otherwise, request permission
  else if (Notification.permission !== "denied") {
    const permission = await Notification.requestPermission();
    if (permission === "granted") {
      new Notification(title, { body });
    }
  }
};

// Helper function to check for break classes
const findUpcomingBreaks = (classes: ClassEntry[]): ClassEntry[] => {
  return classes.filter(item => 
    item.classType && 
    item.classType.toLowerCase().includes('break')
  );
};

// Helper to format break time display
const formatBreakTime = (classItem: ClassEntry): string => {
  if (classItem.time) return classItem.time;
  if (classItem.startTime && classItem.endTime) return `${classItem.startTime} - ${classItem.endTime}`;
  return "Time not specified";
};

// Helper function to check for upcoming holidays or off days
const checkUpcomingHolidaysAndOffDays = (
  holidays: Holiday[], 
  schedule: any, 
  tomorrow: Date
): { isOffDay: boolean; isHoliday: boolean; holidayReason?: string } => {
  const tomorrowStr = tomorrow.toISOString().split('T')[0]; // YYYY-MM-DD
  const tomorrowDay = tomorrow.toLocaleDateString("en-US", { weekday: "long" }); // e.g. "Monday"
  
  // Check if tomorrow is a holiday
  const holidayMatch = holidays.find(h => h.date === tomorrowStr);
  if (holidayMatch) {
    return { isOffDay: false, isHoliday: true, holidayReason: holidayMatch.reason };
  }
  
  // Check if tomorrow is an off day (no classes scheduled)
  if (schedule && schedule.classes && schedule.classes.length > 0) {
    // Filter classes for tomorrow (by day of week)
    const classesForTomorrow = schedule.classes.filter((item: ClassEntry) => {
      return item.day === tomorrowDay;
    });
    
    // If no classes, it's an off day
    if (classesForTomorrow.length === 0) {
      return { isOffDay: true, isHoliday: false };
    }
  }
  
  // Default: not a holiday or off day
  return { isOffDay: false, isHoliday: false };
};

// Add a function to create a meaningful notification message
const createUpcomingDayMessage = (
  tomorrow: Date, 
  isHoliday: boolean,
  isOffDay: boolean, 
  holidayReason?: string
): { subject: string; message: string } => {
  const tomorrowFormatted = format(tomorrow, "EEEE, MMMM d, yyyy");
  
  if (isHoliday) {
    return {
      subject: `Holiday Tomorrow - ${holidayReason || "No Classes"} - TrackLy`,
      message: `This is a reminder that tomorrow (${tomorrowFormatted}) is a holiday${holidayReason ? ` for ${holidayReason}` : ''}. There will be no classes scheduled for this day.`
    };
  }
  
  if (isOffDay) {
    return {
      subject: `Off Day Tomorrow - No Classes - TrackLy`,
      message: `This is a reminder that tomorrow (${tomorrowFormatted}) is an off day according to your schedule. There are no classes scheduled.`
    };
  }
  
  // Should not reach here
  return {
    subject: `Schedule Update - TrackLy`,
    message: `This is an update about your schedule for tomorrow (${tomorrowFormatted}).`
  };
};

// API URL
const API_URL = typeof window !== 'undefined' 
  ? (window.location.hostname === 'localhost' 
      ? 'http://localhost:5000/api' 
      : 'https://trackly-backend.onrender.com/api')
  : 'http://localhost:5000/api';

export function VisualAttendanceForm() {
  const [date, setDate] = useState<Date>(new Date())
  const [isLoadingSchedule, setIsLoadingSchedule] = useState(true)
  const [notes, setNotes] = useState("")
  const [isSaving, setIsSaving] = useState(false)
  const [todaySchedule, setTodaySchedule] = useState<ClassEntry[]>([])
  const [existingRecords, setExistingRecords] = useState<Record<string, any>>({})
  const [allRecords, setAllRecords] = useState<AttendanceRecord[]>([])
  const [holidays, setHolidays] = useState<Holiday[]>([])
  const [holidayReason, setHolidayReason] = useState("")
  const [isHolidayDay, setIsHolidayDay] = useState(false)
  const [selectedClass, setSelectedClass] = useState<ClassEntry | null>(null)
  const [status, setStatus] = useState<"present" | "absent">("present")
  const [scheduleData, setScheduleData] = useState<any>(null)
  const [upcomingBreaks, setUpcomingBreaks] = useState<ClassEntry[]>([])
  const [userEmail, setUserEmail] = useState<string>("")
  const [notificationsEnabled, setNotificationsEnabled] = useState<boolean>(false)
  const [emailNotificationsEnabled, setEmailNotificationsEnabled] = useState<boolean>(false)
  const [lastHolidayNotificationDate, setLastHolidayNotificationDate] = useState<string>("")
  const [isDatePickerOpen, setIsDatePickerOpen] = useState(false)
  const [emailPreferences, setEmailPreferences] = useState({
    attendanceReminders: true,
    breakReminders: true,
    holidayAlerts: true,
    lowAttendanceAlerts: true,
    upcomingDeadlines: true,
    dailySummary: true
  });

  // Load schedule and attendance from database
  useEffect(() => {
    const loadData = async () => {
      const schedule = getFromLocalStorage<{classes: ClassEntry[]}>('schedule', {classes: []});
      setScheduleData(schedule);
      
      const savedHolidays = getFromLocalStorage<string[] | Holiday[]>('holidays', []);
      const holidayDates = Array.isArray(savedHolidays) 
        ? savedHolidays.map(h => typeof h === 'string' ? h : (h as Holiday).date)
        : [];
      setHolidays(holidayDates.map(date => ({ date, reason: "Holiday" })));
      
      try {
        const records = await attendanceService.getAll();
        setAllRecords(records);
      } catch (error) {
        console.error('Failed to load attendance:', error);
      }
      
      updateScheduleForSelectedDate(date, schedule.classes, holidayDates);
      setIsLoadingSchedule(false);
    };
    
    loadData();
    
    window.addEventListener('scheduleUpdated', loadData);
    window.addEventListener('holidaysUpdated', loadData);
    
    return () => {
      window.removeEventListener('scheduleUpdated', loadData);
      window.removeEventListener('holidaysUpdated', loadData);
    };
  }, []);
  
  // Load user preferences
  useEffect(() => {
    // Load user email and preferences from localStorage
    const email = getFromLocalStorage<string>('user_email', '');
    const enableNotifications = getFromLocalStorage<boolean>('enable_notifications', false);
    const enableEmailNotifications = getFromLocalStorage<boolean>('enable_email_notifications', false);
    
    setUserEmail(email);
    setNotificationsEnabled(enableNotifications);
    setEmailNotificationsEnabled(enableEmailNotifications);
    
    // Request notification permission if enabled
    if (enableNotifications && "Notification" in window && Notification.permission !== "granted" && Notification.permission !== "denied") {
      Notification.requestPermission();
    }
    
    // Load the last notification date
    const lastNotificationDate = getFromLocalStorage<string>('last_holiday_notification_date', '');
    setLastHolidayNotificationDate(lastNotificationDate);
  }, []);
  
  // Load email preferences
  useEffect(() => {
    const savedPreferences = getFromLocalStorage('email_preferences', {
      attendanceReminders: true,
      breakReminders: true,
      holidayAlerts: true,
      lowAttendanceAlerts: true,
      upcomingDeadlines: true,
      dailySummary: true
    });
    setEmailPreferences(savedPreferences);
  }, []);
  
  // Check for breaks in today's schedule
  useEffect(() => {
    if (isToday(date) && todaySchedule.length > 0) {
      // Find break-type classes
      const breaks = todaySchedule.filter(item => 
        item.classType && 
        item.classType.toLowerCase().includes('break')
      );
      
      setUpcomingBreaks(breaks);
      
      // Set up timers for break notifications
      const notificationTimers: NodeJS.Timeout[] = [];
      
      breaks.forEach(breakClass => {
        const breakTime = breakClass.startTime || (breakClass.time && breakClass.time.split(" - ")[0]);
        if (breakTime) {
          // Extract hours and minutes
          const [hours, minutes] = breakTime.split(":").map(Number);
          
          // Create a date for the break time today
          const breakDate = new Date();
          breakDate.setHours(hours, minutes, 0, 0);
          
          // Create a date for 15 minutes before the break
          const notificationDate = new Date(breakDate);
          notificationDate.setMinutes(notificationDate.getMinutes() - 15);
          
          // Get time difference in milliseconds
          const now = new Date();
          const timeUntilNotification = notificationDate.getTime() - now.getTime();
          
          // Only set a timer if the break is in the future
          if (timeUntilNotification > 0) {
            // Set timer for 15 minutes before break
            const timer = setTimeout(() => {
              const breakName = breakClass.name || breakClass.subject || "Break";
              const breakRoom = breakClass.room || "Not specified";
              const breakTimeStr = formatBreakTime(breakClass);
              
              // Send browser notification
              if (notificationsEnabled) {
                sendNotification(
                  "Break Coming Up!",
                  `${breakName} in 15 minutes (${breakTimeStr}) at ${breakRoom}`
                );
              }
              
              // Send email notification
              if (emailNotificationsEnabled && userEmail) {
                sendEmail(
                  "Break Reminder - TrackLy",
                  `Your break "${breakName}" is coming up in 15 minutes (${breakTimeStr}) at ${breakRoom}.`,
                  userEmail
                );
              }
              
              // Also show toast
              toast({
                title: "Break Coming Up!",
                description: `${breakName} in 15 minutes (${breakTimeStr}) at ${breakRoom}`,
                variant: "default",
              });
              
            }, timeUntilNotification);
            
            notificationTimers.push(timer);
          }
        }
      });
      
      // Cleanup timers on unmount
      return () => {
        notificationTimers.forEach(timer => clearTimeout(timer));
      };
    }
  }, [todaySchedule, date, notificationsEnabled, emailNotificationsEnabled, userEmail]);
  
  // Check for upcoming holidays/off days and send notifications
  useEffect(() => {
    // Only run if email notifications are enabled and we have a valid email
    if (!emailNotificationsEnabled || !userEmail) return;
    
    // Get tomorrow's date
    const today = new Date();
    const tomorrow = addDays(today, 1);
    const tomorrowStr = tomorrow.toISOString().split('T')[0]; // YYYY-MM-DD
    
    // Check if we've already sent a notification for this date
    if (lastHolidayNotificationDate === tomorrowStr) return;
    
    // Check if tomorrow is a holiday or off day
    const { isHoliday, isOffDay, holidayReason } = checkUpcomingHolidaysAndOffDays(
      holidays, 
      scheduleData, 
      tomorrow
    );
    
    // If tomorrow is either a holiday or off day, send a notification
    if (isHoliday || isOffDay) {
      // Create notification message
      const { subject, message } = createUpcomingDayMessage(
        tomorrow, 
        isHoliday, 
        isOffDay, 
        holidayReason
      );
      
      // Send email notification
      sendEmail(subject, message, userEmail).then(success => {
        if (success) {
          // Record that we've sent a notification for this date
          setLastHolidayNotificationDate(tomorrowStr);
          saveToLocalStorage('last_holiday_notification_date', tomorrowStr);
          
          // Also show toast
          toast({
            title: isHoliday ? "Holiday Tomorrow" : "Off Day Tomorrow",
            description: `Notification sent: ${isHoliday ? `Holiday - ${holidayReason || "No classes"}` : "Off day - No classes"}`,
            variant: "default",
          });
        }
      });
      
      // Also send browser notification if enabled
      if (notificationsEnabled) {
        sendNotification(
          isHoliday ? `Holiday Tomorrow: ${holidayReason || "No Classes"}` : "Off Day Tomorrow - No Classes",
          message
        );
      }
    }
  }, [emailNotificationsEnabled, userEmail, holidays, scheduleData, lastHolidayNotificationDate, notificationsEnabled]);
  
  // Handle saving notification preferences
  const handleNotificationPreferenceChange = (type: 'browser' | 'email', enabled: boolean) => {
    if (type === 'browser') {
      setNotificationsEnabled(enabled);
      saveToLocalStorage('enable_notifications', enabled);
      
      if (enabled && "Notification" in window) {
        Notification.requestPermission();
      }
    } else {
      setEmailNotificationsEnabled(enabled);
      saveToLocalStorage('enable_email_notifications', enabled);
    }
  };
  
  // Handle saving email
  const handleSaveEmail = (email: string) => {
    setUserEmail(email);
    saveToLocalStorage('user_email', email);
    toast({
      title: "Email Saved",
      description: "Your email has been saved for notifications.",
      variant: "default",
    });
  };
  
  // Update schedule when date changes
  useEffect(() => {
    const schedule = getFromLocalStorage<{classes: ClassEntry[]}>('schedule', {classes: []});
    const savedHolidays = getFromLocalStorage<string[]>('holidays', []);
    setHolidays(savedHolidays.map(date => ({ date, reason: "Holiday" })));
    
    updateScheduleForSelectedDate(date, schedule.classes, savedHolidays);
    checkExistingAttendance(date);
  }, [date, allRecords]);
  
  // Check for existing attendance records for this date
  const checkExistingAttendance = (selectedDate: Date) => {
    const dateStr = selectedDate.toISOString().split('T')[0];
    
    const recordsForDate = allRecords.filter((record: AttendanceRecord) => {
      const recordDate = new Date(record.date).toISOString().split('T')[0];
      return recordDate === dateStr;
    });
    
    const recordMap: Record<string, AttendanceRecord> = {};
    
    recordsForDate.forEach((record: AttendanceRecord) => {
      const recordId = record.classId || record.subjectId;
      
      if (recordId) {
        recordMap[recordId] = { 
          id: record.id || `${dateStr}-${recordId}`,
          date: record.date || dateStr,
          classId: recordId,
          className: record.className || "Unknown Class",
          classType: record.classType,
          status: record.status as "present" | "absent", 
          notes: record.notes || "",
          isAutoGenerated: record.isAutoGenerated || false,
          subjectId: record.subjectId
        };
      }
    });
    
    setExistingRecords(recordMap);
  };
  
  // Update the schedule based on selected date
  const updateScheduleForSelectedDate = (selectedDate: Date, classes: ClassEntry[], holidayDates: string[] = []) => {
    const dayOfWeek = selectedDate.toLocaleDateString("en-US", { weekday: "long" });
    const dateStr = selectedDate.toISOString().split('T')[0]; // YYYY-MM-DD
    
    console.log("Updating schedule for date:", dateStr, "Day:", dayOfWeek);
    console.log("Total classes available:", classes.length);
    
    // Check if this date is a holiday
    const isHolidayDate = holidayDates.includes(dateStr);
    setIsHolidayDay(isHolidayDate);
    
    // Get holiday reason if it exists
    if (isHolidayDate) {
      const holidaysData = getFromLocalStorage<string[] | Holiday[]>('holidays', []);
      let reason = "";
      
      if (Array.isArray(holidaysData)) {
        // Check if we have the new format with objects
        const holidayObj = holidaysData.find(h => 
          (typeof h === 'object' && (h as Holiday).date === dateStr) || h === dateStr
        );
        
        if (holidayObj && typeof holidayObj === 'object' && (holidayObj as Holiday).reason) {
          reason = (holidayObj as Holiday).reason;
        } else {
          reason = "Holiday";
        }
      }
      
      setHolidayReason(reason);
      
      // If it's a holiday, set empty schedule
      setTodaySchedule([]);
      return;
    }
    
    // Filter classes for the selected day and exclude break types
    const classesForDay = filterNonBreakClasses(
      classes.filter(item => {
        console.log("Checking class:", item.name, "Day:", item.day);
        return item.day === dayOfWeek;
      })
    );
    
    console.log("Classes for day:", classesForDay.length);
    
    // No longer create temporary classes on off days
    if (classesForDay.length === 0) {
      // This is genuinely an off day, set empty schedule
      setTodaySchedule([]);
      console.log("This is an off day according to schedule.");
    } else {
      // Sort by time
      classesForDay.sort((a, b) => {
        const timeA = a.startTime || (a.time && a.time.split(" - ")[0]) || "00:00";
        const timeB = b.startTime || (b.time && b.time.split(" - ")[0]) || "00:00";
        return timeA.localeCompare(timeB);
      });
      
      setTodaySchedule(classesForDay);
    }
  };
  
  // Helper to save attendance to database
  const saveAttendanceToDb = async (updatedRecords: AttendanceRecord[]) => {
    try {
      await attendanceService.save(updatedRecords);
      setAllRecords(updatedRecords);
      window.dispatchEvent(new Event('attendanceUpdated'));
    } catch (error) {
      console.error('Failed to save attendance:', error);
      toast({
        title: "Error",
        description: "Failed to save attendance to database.",
        variant: "destructive"
      });
    }
  };

  // Handle all day present/absent
  const handleAllDay = async (allDayStatus: "present" | "absent") => {
    const nonBreakClasses = filterNonBreakClasses(todaySchedule);
    
    if (nonBreakClasses.length === 0) {
      toast({
        title: "No Classes",
        description: "There are no classes scheduled for this day.",
        variant: "destructive",
      });
      return;
    }
    
    setIsSaving(true);
    
    try {
      const updatedRecords = [...allRecords];
      const localStateUpdates: Record<string, any> = { ...existingRecords };
      
      for (const classEntry of nonBreakClasses) {
        const className = classEntry.name || classEntry.subject || "Unknown Class";
        const classId = classEntry.id;
        const classType = classEntry.classType || "Unknown";
        
        if (!className || !classId) continue;
        
        const attendanceRecord = {
          id: crypto.randomUUID(),
          date: date.toISOString(),
          classId: classId,
          className: className,
          classType: classType,
          time: classEntry.time || (classEntry.startTime && classEntry.endTime 
            ? `${classEntry.startTime} - ${classEntry.endTime}` 
            : undefined),
          room: classEntry.room,
          status: allDayStatus,
          notes: allDayStatus === "absent" ? "Marked absent for entire day" : "Marked present for entire day",
          isAutoGenerated: false,
          subjectId: classId
        };
        
        const existingIndex = updatedRecords.findIndex(r => 
          r.date === attendanceRecord.date && r.classId === classId
        );
        
        if (existingIndex >= 0) {
          updatedRecords[existingIndex] = attendanceRecord;
        } else {
          updatedRecords.push(attendanceRecord);
        }
        
        localStateUpdates[classId] = attendanceRecord;
      }
      
      await saveAttendanceToDb(updatedRecords);
      setNotes("");
      setExistingRecords(localStateUpdates);
      
      toast({
        title: "Success",
        description: `All classes for ${format(date, 'EEE, MMM d')} marked as ${allDayStatus === "present" ? "present" : "absent"}`,
        variant: allDayStatus === "present" ? "default" : "destructive"
      });
      
      if (allDayStatus === "present") {
        showSuccessNotification(
          "All Marked Present",
          `All ${nonBreakClasses.length} classes for ${format(date, 'EEE, MMM d')} have been marked as present.`,
          {
            action: {
              label: "View Details",
              onClick: () => {
                document.querySelector(".attendance-classes")?.scrollIntoView({ behavior: "smooth" });
              }
            }
          }
        );
      } else {
        showWarningNotification(
          "All Marked Absent",
          `All ${nonBreakClasses.length} classes for ${format(date, 'EEE, MMM d')} have been marked as absent.`,
          {
            action: {
              label: "Undo",
              onClick: () => {
                handleAllDay("present");
              }
            }
          }
        );
      }
    } catch (error) {
      console.error("Error marking attendance:", error);
      toast({
        title: "Error",
        description: "Failed to mark attendance",
        variant: "destructive"
      });
    } finally {
      setIsSaving(false);
    }
  };
  
  // Handle marking a date as holiday or removing holiday status
  const handleHolidayToggle = () => {
    const dateStr = date.toISOString().split('T')[0]; // YYYY-MM-DD
    const holidaysData = getFromLocalStorage<string[] | Holiday[]>('holidays', []);
    
    // Convert to new format if it's the old format
    const updatedHolidays: Holiday[] = Array.isArray(holidaysData) ? 
      holidaysData.map(h => typeof h === 'string' ? { date: h, reason: "Holiday" } : h as Holiday) : [];
    
    if (isHolidayDay) {
      // Remove from holidays
      const filteredHolidays = updatedHolidays.filter(h => h.date !== dateStr);
      
      setIsHolidayDay(false);
      setHolidayReason("");
      
      // Update UI to show schedule
      const schedule = getFromLocalStorage<{classes: ClassEntry[]}>('schedule', {classes: []});
      const holidayDates = filteredHolidays.map(h => h.date);
      updateScheduleForSelectedDate(date, schedule.classes, holidayDates);
      
      toast({
        title: "Holiday Removed",
        description: `${format(date, 'PPP')} is no longer marked as a holiday.`
      });
      
      showSuccessNotification(
        "Holiday Removed", 
        `${format(date, 'PPP')} has been removed from the holiday list and will now count towards attendance.`
      );
      
      // Save updated holidays
      saveToLocalStorage('holidays', filteredHolidays);
      setHolidays(filteredHolidays);
    } else {
      // Show prompt for holiday reason
      const reason = prompt("Enter reason for this holiday:", "");
      
      if (reason !== null) {
        // Add to holidays with reason
        const newHoliday = { date: dateStr, reason: reason || "Holiday" };
        updatedHolidays.push(newHoliday);
        
        const holidayDates = updatedHolidays.map(h => h.date);
        
        setIsHolidayDay(true);
        setHolidayReason(reason || "Holiday");
        
        // Clear schedule for this day
        setTodaySchedule([]);
        
              toast({
        title: "Holiday Marked",
        description: `${format(date, 'PPP')} has been marked as a holiday and will not count towards attendance.`
      });
      
      showSuccessNotification(
        "Holiday Marked", 
        `${format(date, 'PPP')} has been marked as a holiday: ${reason || "Holiday"}. This day will not count towards attendance calculations.`,
        {
          action: {
            label: "View Calendar",
            onClick: () => {
              // Focus on the calendar
              document.querySelector(".calendar-container")?.scrollIntoView({ behavior: "smooth" });
            }
          }
        }
      );
        
        // Save updated holidays
        saveToLocalStorage('holidays', updatedHolidays);
        setHolidays(updatedHolidays);
      }
    }
    
    // Trigger event for other components
    const event = new CustomEvent('holidaysUpdated');
    window.dispatchEvent(event);
  };
  
  const handleDirectAttendance = async (classId: string, attendanceStatus: "present" | "absent") => {
    setIsSaving(true);
    
    try {
      const classEntry = todaySchedule.find(item => item.id === classId);
      if (!classEntry) {
        throw new Error("Class not found");
      }
      
      const updatedRecords = [...allRecords];
      const formattedDate = format(date, 'yyyy-MM-dd');
      const recordId = `${formattedDate}-${classId}`;
      
      const existingIndex = updatedRecords.findIndex(record => 
        record.id === recordId || 
        (record.date === formattedDate && record.classId === classId)
      );
      
      const isToggle = existingIndex >= 0 && updatedRecords[existingIndex].status === attendanceStatus;
      const updatedStateRecords = { ...existingRecords };
      
      if (isToggle) {
        if (existingIndex >= 0) {
          updatedRecords.splice(existingIndex, 1);
        }
        delete updatedStateRecords[classId];
        
        await saveAttendanceToDb(updatedRecords);
        setExistingRecords(updatedStateRecords);
        
        toast({
          title: "Reset Attendance",
          description: `Attendance for ${classEntry.name || classEntry.subject || "Unknown Class"} has been reset`,
          variant: "default"
        });
      } else {
        const className = classEntry.name || classEntry.subject || "Unknown Class";
        const classType = classEntry.classType || "Unknown";
        
        const attendanceRecord = {
          id: recordId,
          date: formattedDate,
          classId: classId,
          className: className,
          classType: classType,
          time: classEntry.time || (classEntry.startTime && classEntry.endTime 
            ? `${classEntry.startTime} - ${classEntry.endTime}` 
            : undefined),
          room: classEntry.room,
          status: attendanceStatus,
          notes: notes,
          createdAt: new Date().toISOString(),
          subjectId: classId
        };
        
        if (existingIndex >= 0) {
          updatedRecords[existingIndex] = attendanceRecord;
        } else {
          updatedRecords.push(attendanceRecord);
        }
        
        await saveAttendanceToDb(updatedRecords);
        updatedStateRecords[classId] = attendanceRecord;
        setExistingRecords(updatedStateRecords);
        
        toast({
          title: "Attendance Recorded",
          description: `Marked ${attendanceStatus} for ${className}`,
          variant: attendanceStatus === "present" ? "default" : "destructive"
        });
      }
    } catch (error) {
      console.error("Error recording attendance:", error);
      const errorMessage = error instanceof Error ? error.message : "Failed to record attendance";
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive"
      });
    } finally {
      setIsSaving(false);
    }
  };
  
  // Auto-mark all classes at end of day if not already marked
  const autoMarkEndOfDayAttendance = () => {
    // Only auto-mark if this is a past day
    if (!isBefore(date, startOfDay(new Date()))) {
      return;
    }
    
    if (isHolidayDay || todaySchedule.length === 0) {
      return;
    }
    
    // Get attendance records
    const records = getFromLocalStorage<any[]>('attendance_records', []);
    const formattedDate = format(date, 'yyyy-MM-dd');
    
    // Track if we added any new records
    let addedRecords = false;
    const updatedRecords: Record<string, any> = { ...existingRecords };
    
    // Go through all classes for today and auto-mark as present if not already marked
    todaySchedule.forEach(classEntry => {
      const classId = classEntry.id;
      
      // Skip if already has attendance
      if (existingRecords[classId]) {
        return;
      }
      
      // Get the class name
      const className = classEntry.name || classEntry.subject || "Unknown Class";
      
      // Create a unique ID for this attendance record
      const recordId = `${formattedDate}-${classId}`;
      
      // Create the attendance record
      const attendanceRecord = {
        id: recordId,
        date: formattedDate,
        classId: classId,
        className: className,
        classType: classEntry.classType || "Lecture",
        time: classEntry.time || (classEntry.startTime && classEntry.endTime 
          ? `${classEntry.startTime} - ${classEntry.endTime}` 
          : undefined),
        room: classEntry.room,
        status: "present", // Auto-mark as present
        notes: "Automatically marked as present at end of day",
        isAutoGenerated: true, // Flag to identify auto-generated records
        createdAt: new Date().toISOString(),
        subjectId: classId
      };
      
      // Add to records
      records.push(attendanceRecord);
      updatedRecords[classId] = attendanceRecord;
      addedRecords = true;
    });
    
    if (addedRecords) {
      // Save to localStorage
      saveToLocalStorage('attendance_records', records);
      
      // Update local state
      setExistingRecords(updatedRecords);
      
      // Show success message
      toast({
        title: "Auto Attendance",
        description: `Unmarked classes for ${format(date, 'EEE, MMM d')} were automatically marked as present`,
        variant: "default"
      });
      
      // Show modern popup notification
      showInfoNotification(
        "Auto-Attendance Applied",
        `${updatedRecords.length} unmarked classes for ${format(date, 'EEE, MMM d')} were automatically marked as present.`,
        {
          action: {
            label: "View Auto-Marked",
            onClick: () => {
              // Navigate to auto-marked page
              window.location.href = "/attendance?tab=auto-marked";
            }
          }
        }
      );
    }
  };

  // Setup interval to check for end-of-day auto-marking
  useEffect(() => {
    // Check every 10 minutes
    const interval = setInterval(() => {
      autoMarkEndOfDayAttendance();
    }, 10 * 60 * 1000);
    
    // Run once on component mount
    autoMarkEndOfDayAttendance();
    
    return () => clearInterval(interval);
  }, []);
  
  // Add this new function to handle manual attendance recording
  const handleManualAttendanceRecord = () => {
    const selectedClassId = selectedClass?.id;
    
    if (!selectedClassId || !selectedClass) {
      toast({
        title: "No Class Selected",
        description: "Please select a class to record attendance for",
        variant: "destructive",
      });
      return;
    }
    
    handleDirectAttendance(selectedClassId, status);
  };

  // Send daily attendance reminder
  useEffect(() => {
    if (!emailPreferences.attendanceReminders || !userEmail) return;

    const sendReminders = async () => {
      // Only send reminders for future dates
      if (isToday(date) || isBefore(date, new Date())) return;

      // Send reminder for upcoming classes
      if (todaySchedule.length > 0) {
        try {
          // Create a notification in localStorage instead of sending an email
          const formattedDate = format(date, 'EEEE, MMMM d, yyyy');
          const subjectList = todaySchedule
            .map(subject => `- ${subject.name || subject.subject || 'Unknown Class'} (${subject.time || 'Time not specified'})`)
            .join('\n');
          
          // Get existing notifications from localStorage
          const existingNotifications = getFromLocalStorage<any[]>('notifications', []) || [];
          
          // Add new notification
          const newNotification = {
            id: `notification_${Date.now()}`,
            title: `Classes Reminder for ${formattedDate}`,
            message: `This is a reminder about your classes for ${formattedDate}.\n\nScheduled Classes:\n${subjectList}\n\nPlease remember to mark your attendance for these classes.`,
            type: 'attendance',
            isRead: false,
            createdAt: new Date().toISOString()
          };
          
          // Add to beginning of array (newest first)
          existingNotifications.unshift(newNotification);
          
          // Save back to localStorage
          localStorage.setItem('notifications', JSON.stringify(existingNotifications));
          
          // Show success message
          toast({
            title: "Reminder Set",
            description: `Reminder set for classes on ${formattedDate}`,
            variant: "default"
          });
        } catch (error) {
          console.error('Error creating attendance reminder:', error);
        }
      }
    };

    sendReminders();
  }, [date, todaySchedule, emailPreferences.attendanceReminders, userEmail]);

  // Send daily summary at the end of each day
  useEffect(() => {
    if (!emailPreferences.dailySummary || !userEmail) return;

    const sendEndOfDaySummary = async () => {
      // Only send summary for past dates
      if (!isBefore(date, new Date())) return;

      // Get attendance records for the day
      const records = Object.values(existingRecords);

      // Get upcoming holidays
      const nextWeek = Array.from({length: 7}, (_, i) => addDays(new Date(), i + 1));
      const upcomingHolidays = nextWeek
        .map(date => {
          const dateStr = date.toISOString().split('T')[0];
          return holidays.find(h => h.date === dateStr);
        })
        .filter(Boolean);

      await sendDailySummary(date, records, upcomingHolidays);
    };

    // Only run once per day
    const lastSummaryDate = getFromLocalStorage<string>('last_summary_date', '');
    const today = new Date().toISOString().split('T')[0];
    
    if (lastSummaryDate !== today) {
      sendEndOfDaySummary();
      saveToLocalStorage('last_summary_date', today);
    }
  }, [date, existingRecords, holidays, emailPreferences.dailySummary, userEmail]);

  // Handle email preference changes
  const handleEmailPreferenceChange = (key: string, value: boolean) => {
    const updatedPreferences = {
      ...emailPreferences,
      [key]: value
    };
    setEmailPreferences(updatedPreferences);
    saveEmailPreferences(updatedPreferences);
  };

  return (
    <div className="w-full">
      <TooltipProvider>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Side - Calendar */}
        <Card className="w-full">
          <CardContent className="pt-6">
            <Calendar
              mode="single"
              selected={date}
              onSelect={(newDate) => setDate(newDate || new Date())}
              className="border rounded-md p-4"
              modifiers={{
                holiday: (day) => {
                  const dayStr = day.toISOString().split('T')[0];
                    return holidays.some(h => h.date === dayStr);
                }
              }}
              modifiersClassNames={{
                holiday: "bg-yellow-100 text-yellow-900 font-medium"
              }}
            />
            
            <div className="mt-4 text-center">
              <p className="text-sm text-muted-foreground">
                Selected date: <span className="font-medium">{format(date, 'PPP')}</span>
                {isToday(date) && (
                  <Badge className="ml-2 bg-blue-500">Today</Badge>
                )}
                  {isHolidayDay && (
                  <Badge className="ml-2 bg-yellow-500">Holiday</Badge>
                )}
              </p>
              
              <div className="mt-4">
                  {isHolidayDay ? (
                  <div className="py-4 px-2 border border-dashed rounded-lg border-yellow-400 bg-yellow-50">
                    <p className="text-base font-medium text-yellow-700">Holiday</p>
                      <p className="text-sm text-yellow-600 mt-1">
                        {holidayReason ? holidayReason : "This day is marked as a holiday"}
                      </p>
                      <p className="text-xs text-yellow-600 mt-1">Holidays don't count in attendance calculations</p>
                  </div>
                ) : todaySchedule.length > 0 ? (
                  <>
                    <p className="text-sm font-medium mb-2">
                      {`${todaySchedule.length} classes scheduled`}
                    </p>
                    <div className="flex flex-wrap gap-2 justify-center">
                      {todaySchedule.map((classItem, index) => (
                        <Badge 
                          key={index} 
                          variant="outline"
                          className="flex items-center gap-1"
                        >
                          <BookOpen className="h-3 w-3" />
                          <span>
                              {classItem.name || classItem.subject}
                            {classItem.classType && ` (${classItem.classType})`}
                          </span>
                        </Badge>
                      ))}
                    </div>
                  </>
                ) : (
                  <div className="py-4 px-2 border border-dashed rounded-lg border-muted-foreground/20">
                      <p className="text-base font-medium text-muted-foreground">Off Day</p>
                      <p className="text-sm text-muted-foreground mt-1">
                        According to your uploaded schedule, {format(date, 'EEEE')} is an off day
                      </p>
                      <p className="text-xs text-muted-foreground mt-1">
                        No classes are scheduled on this day in your timetable
                      </p>
                  </div>
                )}
              </div>
              
                <LoadingButton
                className={cn(
                  "mt-4",
                    isHolidayDay 
                    ? "bg-yellow-100 text-yellow-900 hover:bg-yellow-200 border border-yellow-300" 
                    : "bg-yellow-500 text-white hover:bg-yellow-600"
                )}
                variant="outline"
                onClick={handleHolidayToggle}
                  loadingText={isHolidayDay ? "Removing..." : "Marking..."}
                  successText={isHolidayDay ? "Removed!" : "Marked!"}
              >
                <CalendarIcon2 className="mr-2 h-4 w-4" />
                  {isHolidayDay ? "Remove Holiday" : "Mark as Holiday"}
                </LoadingButton>
            </div>
          </CardContent>
        </Card>
        
        {/* Right Side - Form Options */}
        <Card className="w-full">
          <CardContent className="pt-6 space-y-5">
              {/* Show different content based on if it's a holiday, has classes, or is an off day */}
              {isHolidayDay ? (
                <div className="flex flex-col items-center gap-2 py-6">
                  <div className="text-yellow-500">
                    <CalendarIcon2 className="h-16 w-16" />
                </div>
                  <p className="text-xl font-medium text-yellow-700">Holiday</p>
                  {holidayReason && (
                    <Badge variant="outline" className="bg-yellow-100 text-yellow-800 border-yellow-300">
                      {holidayReason}
                    </Badge>
                  )}
                  <p className="text-center text-yellow-600 max-w-md mt-2">
                    This day is marked as a holiday. No attendance will be recorded or counted
                    towards your attendance statistics.
                  </p>
                  <LoadingButton 
                    variant="outline"
                    className="mt-4 border-yellow-300 text-yellow-700 hover:bg-yellow-50"
                    onClick={handleHolidayToggle}
                    loadingText="Removing..."
                    successText="Removed!"
                  >
                    Remove Holiday Status
                  </LoadingButton>
                </div>
              ) : todaySchedule.length === 0 ? (
                <div className="flex flex-col items-center gap-2 py-6">
                  <div className="text-muted-foreground">
                    <CalendarIcon2 className="h-12 w-12 opacity-50" />
                  </div>
                  <p className="text-xl font-medium text-muted-foreground">Off Day</p>
                  <div className="mt-5 p-5 border rounded-lg text-center bg-muted/5 max-w-md">
                    <h4 className="text-sm font-medium text-muted-foreground mb-2">No Classes Available</h4>
                    <p className="text-sm text-muted-foreground">
                      According to your uploaded schedule, {format(date, 'EEEE')} is an off day
                    </p>
                    <p className="text-xs text-muted-foreground mt-2">
                      No classes are scheduled for this day in your academic timetable
                    </p>
                  </div>
                  <div className="mt-4 flex gap-2">
                    <LoadingButton 
                      variant="outline"
                      size="sm"
                      className="border-yellow-300 text-yellow-700 hover:bg-yellow-50 flex items-center gap-1"
                      onClick={handleHolidayToggle}
                      loadingText="Marking..."
                      successText="Marked!"
                    >
                      <CalendarIcon2 className="h-4 w-4" />
                      Mark as Holiday
                    </LoadingButton>
                  </div>
                </div>
              ) : (
                <>
                  {/* Subject Selection - Only show when there are classes */}
                  <div>
                    <Label className="text-base font-medium">Classes</Label>
                <div className="mt-2">
                      <h3 className="text-sm font-medium mb-3 text-center">
                        Classes for {format(date, 'EEEE, MMMM d')} 
                        <Badge variant="outline" className="ml-2">{todaySchedule.length} classes</Badge>
                        {isBefore(date, startOfDay(new Date())) && (
                          <Badge variant="outline" className="ml-2 bg-blue-100 text-blue-700 border-blue-300">Past Day</Badge>
                        )}
                      </h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    {todaySchedule.map((classItem, index) => {
                          const className = classItem.name || classItem.subject || "Unnamed Class";
                          const classId = classItem.id;
                          
                          const hasAttendance = Boolean(existingRecords[classId]);
                          const attendanceStatus = hasAttendance ? existingRecords[classId]?.status : null;
                          const isAutoGenerated = hasAttendance && Boolean(existingRecords[classId]?.isAutoGenerated);
                          const isSelected = selectedClass?.id === classId;
                          
                          return (
                        <div 
                          key={index}
                          className={cn(
                                "border rounded-md p-3 transition-all relative overflow-hidden cursor-pointer",
                                hasAttendance 
                                ? attendanceStatus === "present" 
                                    ? isAutoGenerated 
                                      ? "bg-blue-50 border-blue-300" 
                                      : "bg-green-50 border-green-300"
                                    : "bg-red-50 border-red-300" 
                                  : "bg-background hover:bg-muted/50 border-border",
                                isSelected && "ring-2 ring-primary ring-offset-1"
                              )}
                              onClick={() => setSelectedClass(classItem)}
                            >
                              {hasAttendance && (
                                <div className={cn(
                                  "absolute top-0 left-0 w-1 h-full",
                                  attendanceStatus === "present" 
                                    ? isAutoGenerated 
                                      ? "bg-blue-500" 
                                      : "bg-green-500" 
                                    : "bg-red-500"
                                )}/>
                              )}
                          <div className="flex items-center justify-between">
                            <div className="flex flex-col overflow-hidden">
                              <div className="flex items-center">
                                <div className={cn(
                                  "w-3 h-3 rounded-full mr-2 flex-shrink-0",
                                  hasAttendance
                                    ? attendanceStatus === "present" 
                                          ? isAutoGenerated
                                            ? "bg-blue-500" 
                                            : "bg-green-500" 
                                      : "bg-red-500"
                                    : "bg-gray-300"
                                )}/>
                                    <span className={cn(
                                      "font-medium text-sm truncate",
                                      hasAttendance
                                        ? attendanceStatus === "present" 
                                          ? isAutoGenerated
                                            ? "text-blue-800"
                                            : "text-green-800" 
                                          : "text-red-800"
                                        : ""
                                    )}>{className}</span>
                                    {hasAttendance && (
                                      <span className={cn(
                                        "ml-2 text-xs px-1.5 py-0.5 rounded-full font-semibold",
                                        attendanceStatus === "present" 
                                          ? isAutoGenerated
                                            ? "bg-blue-200 text-blue-800" 
                                            : "bg-green-200 text-green-800" 
                                          : "bg-red-200 text-red-800"
                                      )}>
                                        {attendanceStatus === "present" 
                                          ? isAutoGenerated 
                                            ? "Auto-Present" 
                                            : "Present" 
                                          : "Absent"}
                                      </span>
                                    )}
                              </div>
                              <div className="flex items-center gap-1 ml-5 mt-1">
                                {classItem.classType && (
                                      <Badge variant="outline" className={cn(
                                        "text-xs px-1 py-0 h-4",
                                        hasAttendance
                                          ? attendanceStatus === "present" 
                                            ? isAutoGenerated
                                              ? "border-blue-300 text-blue-800 bg-blue-100"
                                              : "border-green-300 text-green-800 bg-green-100" 
                                            : "border-red-300 text-red-800 bg-red-100"
                                          : ""
                                      )}>
                                    {classItem.classType}
                                  </Badge>
                                )}
                                {classItem.time && (
                                      <span className={cn(
                                        "text-xs ml-1 flex items-center",
                                        hasAttendance
                                          ? attendanceStatus === "present" 
                                            ? isAutoGenerated
                                              ? "text-blue-700"
                                              : "text-green-700" 
                                            : "text-red-700"
                                          : "text-muted-foreground"
                                      )}>
                                        <CalendarIcon className="h-3 w-3 mr-1 inline" />
                                    {classItem.time}
                                  </span>
                                )}
                                {classItem.room && (
                                      <span className={cn(
                                        "text-xs ml-1 flex items-center",
                                        hasAttendance
                                          ? attendanceStatus === "present" 
                                            ? isAutoGenerated
                                              ? "text-blue-700"
                                              : "text-green-700" 
                                            : "text-red-700"
                                          : "text-muted-foreground"
                                      )}>
                                        <Map className="h-3 w-3 mr-1 inline" />
                                        {classItem.room}
                                      </span>
                                    )}
                                    {isAutoGenerated && (
                                    <Tooltip>
                                      <TooltipTrigger asChild>
                                          <span className="text-xs ml-1 flex items-center text-blue-600">
                                            <Clock className="h-3 w-3 mr-1 inline" />
                                            Auto
                                          </span>
                                      </TooltipTrigger>
                                      <TooltipContent>
                                          <p>Automatically marked as present because this is a past class</p>
                                      </TooltipContent>
                                    </Tooltip>
                                )}
                              </div>
                            </div>
                              </div>
                          </div>
                          );
                    })}
                  </div>
                      <p className="text-xs text-muted-foreground text-center mt-3">
                        Click on a class to select it, then use the Record Attendance section below
                        {isBefore(date, startOfDay(new Date())) && (
                          <span className="block mt-1 text-blue-600">
                            <Clock className="h-3 w-3 inline mr-1" />
                            Past classes are automatically marked as present unless manually changed
                          </span>
                        )}
                  </p>
                </div>
            </div>
            
                  {/* Quick Actions - Only for days with classes */}
                <div>
                    <Label className="text-base font-medium">Quick Actions</Label>
                    <div className="flex items-center justify-between mb-4 space-x-2">
                      <div className="flex items-center gap-2">
                        <LoadingButton 
                          onClick={() => handleAllDay("present")}
                          variant="default" 
                          size="sm" 
                          className="flex items-center gap-1"
                          loadingText="Marking..."
                          successText="Marked All Present!"
                        >
                          <CheckCircle className="h-4 w-4" /> Mark All Present
                        </LoadingButton>
                        <LoadingButton 
                          onClick={() => handleAllDay("absent")}
                          variant="outline" 
                          size="sm" 
                          className="flex items-center gap-1 border-red-200 text-red-600 hover:bg-red-50"
                          loadingText="Marking..."
                          successText="Marked All Absent!"
                        >
                          <XCircle className="h-4 w-4" /> Mark All Absent
                        </LoadingButton>
                      </div>
                                            
                    </div>
                    
                    {/* Add manual attendance recording section */}
                    <div className="mt-4 p-3 border rounded-md">
                      <h3 className="text-sm font-medium mb-2">Manual Attendance Recording</h3>
                      <p className="text-xs text-muted-foreground mb-3">
                        Select a class above, then choose an attendance status and click Record
                      </p>
                      
                      <div className="flex items-center gap-2">
                        <div className="flex-1 flex items-center">
                    <Button
                      type="button"
                            size="sm"
                      variant={status === "present" ? "default" : "outline"}
                      className={cn(
                              "flex-1",
                              status === "present" && "bg-green-600 hover:bg-green-700"
                      )}
                            onClick={() => setStatus("present")}
                    >
                            <Check className="mr-1 h-4 w-4" />
                      Present
                    </Button>
                    <Button
                      type="button"
                            size="sm"
                      variant={status === "absent" ? "default" : "outline"}
                      className={cn(
                              "flex-1 ml-1",
                              status === "absent" && "bg-red-600 hover:bg-red-700"
                      )}
                            onClick={() => setStatus("absent")}
                    >
                            <X className="mr-1 h-4 w-4" />
                      Absent
                    </Button>
                  </div>
                        <LoadingButton
                          type="button"
                          onClick={handleManualAttendanceRecord}
                          disabled={!selectedClass || isSaving}
                          className="whitespace-nowrap"
                          loadingText="Recording..."
                          successText="Recorded!"
                        >
                          Record Attendance
                        </LoadingButton>
                      </div>
                      
                      <p className="text-xs mt-2 text-center text-muted-foreground">
                        {selectedClass 
                          ? `Selected: ${selectedClass.name || selectedClass.subject || "Unknown Class"}`
                          : "No class selected"}
                      </p>
                    </div>
                    
                    <p className="text-xs text-muted-foreground mt-2 text-center">
                      Click the same attendance button twice to clear the attendance status
                    </p>
                </div>
                
                  {/* Add break notification section */}
                  {isToday(date) && (
                <div>
                      <Label className="text-base font-medium">Break Notifications</Label>
                      
                      {upcomingBreaks.length > 0 ? (
                        <div className="mt-2 border rounded-md p-3 bg-blue-50 border-blue-200">
                          <div className="flex items-center gap-1 mb-3">
                            <Bell className="h-4 w-4 text-blue-600" />
                            <span className="text-sm font-medium text-blue-700">
                              Scheduled Breaks ({upcomingBreaks.length})
                            </span>
                          </div>
                          
                          {/* List breaks */}
                          <div className="space-y-2 mb-3">
                            {upcomingBreaks.map((breakItem, idx) => (
                              <div 
                                key={idx} 
                                className="flex justify-between items-center text-xs p-2 bg-blue-100 rounded border border-blue-200"
                              >
                                <div className="flex flex-col">
                                  <span className="font-medium">
                                    {breakItem.name || breakItem.subject || "Break"}
                                  </span>
                                  <div className="flex items-center gap-1 mt-0.5 text-blue-700">
                                    <Clock className="h-3 w-3" />
                                    <span>
                                      {formatBreakTime(breakItem)}
                                    </span>
                                    <Map className="h-3 w-3 ml-2" />
                                    <span>
                                      {breakItem.room || "No room"}
                                    </span>
                                  </div>
                                </div>
                                <Badge className="bg-blue-200 border-blue-300 text-blue-800">
                                  Break
                                </Badge>
                              </div>
                            ))}
                          </div>
                          
                          {/* Notification settings */}
                          <div className="space-y-3 pt-2 border-t border-blue-200">
                            <div className="flex items-center justify-between">
                              <div className="text-sm">
                                Browser Notifications
                                <p className="text-xs text-blue-600">
                                  Popup alerts 15 minutes before breaks
                                </p>
                              </div>
                    <Button
                                size="sm" 
                                variant={notificationsEnabled ? "default" : "outline"}
                                className={notificationsEnabled ? "bg-blue-600" : ""}
                                onClick={() => handleNotificationPreferenceChange('browser', !notificationsEnabled)}
                              >
                                {notificationsEnabled ? "Enabled" : "Enable"}
                    </Button>
                            </div>
                            
                            <div className="flex items-center justify-between">
                              <div className="text-sm">
                                Email Notifications
                                <p className="text-xs text-blue-600">
                                  Receive email alerts for breaks
                                </p>
                              </div>
                    <Button
                                size="sm" 
                                variant={emailNotificationsEnabled ? "default" : "outline"}
                                className={emailNotificationsEnabled ? "bg-blue-600" : ""}
                                onClick={() => handleNotificationPreferenceChange('email', !emailNotificationsEnabled)}
                              >
                                {emailNotificationsEnabled ? "Enabled" : "Enable"}
                    </Button>
                  </div>
                            
                            {emailNotificationsEnabled && (
                              <div className="flex items-center gap-2">
                                <Input 
                                  type="email"
                                  placeholder="Enter your email address"
                                  value={userEmail}
                                  onChange={(e) => setUserEmail(e.target.value)}
                                  className="text-sm h-8"
                                />
                                <Button 
                                  size="sm"
                                  onClick={() => handleSaveEmail(userEmail)}
                                  disabled={!userEmail || !userEmail.includes('@')}
                                >
                                  Save
                                </Button>
                              </div>
                            )}
                          </div>
                        </div>
                      ) : (
                        <div className="mt-2 border border-dashed rounded-md p-3 text-center">
                          <p className="text-sm text-muted-foreground">
                            No breaks scheduled for today
                          </p>
                          <p className="text-xs text-muted-foreground mt-1">
                            Break times would appear here if scheduled
                  </p>
                </div>
                      )}
                    </div>
                  )}
                
                  {/* Add the UI for displaying holiday notifications */}
                  {emailNotificationsEnabled && (
                <div>
                      <Label className="text-base font-medium mt-5">Upcoming Notifications</Label>
                      
                      <div className="mt-2 border rounded-md p-3 bg-amber-50 border-amber-200">
                        <div className="flex items-center gap-1 mb-2">
                          <CalendarIcon2 className="h-4 w-4 text-amber-600" />
                          <span className="text-sm font-medium text-amber-700">
                            Holiday & Off Day Alerts
                          </span>
                </div>
                
                        <p className="text-xs text-amber-700 mb-3">
                          You will receive automatic email notifications one day before holidays and off days.
                        </p>
                        
                        {(() => {
                          // Check for upcoming holiday or off day
                          const today = new Date();
                          const tomorrow = addDays(today, 1);
                          const tomorrowStr = tomorrow.toISOString().split('T')[0];
                          
                          // Check if tomorrow is a holiday or off day
                          const { isHoliday, isOffDay, holidayReason } = checkUpcomingHolidaysAndOffDays(
                            holidays, 
                            scheduleData, 
                            tomorrow
                          );
                          
                          if (isHoliday || isOffDay) {
                            // Determine if notification was already sent
                            const alreadyNotified = lastHolidayNotificationDate === tomorrowStr;
                            
                            return (
                              <div className={cn(
                                "p-2 rounded border text-sm flex items-center justify-between",
                                alreadyNotified 
                                  ? "bg-amber-100 border-amber-300" 
                                  : "bg-amber-200 border-amber-400"
                              )}>
                                <div className="flex items-center gap-2">
                                  {isHoliday ? (
                                    <span className="text-amber-800">
                                      <strong>Holiday tomorrow:</strong> {holidayReason || "No classes"}
                                    </span>
                                  ) : (
                                    <span className="text-amber-800">
                                      <strong>Off day tomorrow:</strong> No classes
                                    </span>
                                  )}
                                </div>
                                
                                {alreadyNotified ? (
                                  <Badge className="bg-green-100 text-green-800 border-green-300">
                                    Notification Sent
                                  </Badge>
                                ) : (
                                  <Badge className="bg-amber-200 text-amber-800 border-amber-400">
                                    Notification Pending
                                  </Badge>
                                )}
                              </div>
                            );
                          }
                          
                          // Check if there are any upcoming holidays in the next 7 days
                          const nextWeek = Array.from({length: 7}, (_, i) => addDays(today, i + 1));
                          const upcomingHolidays = nextWeek
                            .map(date => {
                              const dateStr = date.toISOString().split('T')[0];
                              const holiday = holidays.find(h => h.date === dateStr);
                              if (holiday) {
                                return { 
                                  dateValue: date, 
                                  date: holiday.date,
                                  reason: holiday.reason 
                                };
                              }
                              
                              // Check if it's an off day
                              const dayOfWeek = date.toLocaleDateString("en-US", { weekday: "long" });
                              if (scheduleData && scheduleData.classes) {
                                const classesForDay = scheduleData.classes.filter((c: ClassEntry) => c.day === dayOfWeek);
                                if (classesForDay.length === 0) {
                                  return { 
                                    dateValue: date, 
                                    date: dateStr,
                                    isOffDay: true,
                                    reason: "Off Day" 
                                  };
                                }
                              }
                              
                              return null;
                            })
                            .filter(Boolean);
                          
                          if (upcomingHolidays.length > 0) {
                            return (
                              <div className="space-y-2">
                                <p className="text-xs font-medium text-amber-800">Upcoming holidays/off days:</p>
                                {upcomingHolidays.slice(0, 3).map((holiday: any, idx) => (
                                  <div key={idx} className="flex items-center justify-between text-xs p-1.5 bg-amber-100 rounded border border-amber-200">
                                    <span>{format(holiday.dateValue, "EEE, MMM d")}</span>
                                    <Badge className={cn(
                                      "text-xs",
                                      holiday.isOffDay 
                                        ? "bg-gray-100 text-gray-800 border-gray-300"
                                        : "bg-amber-200 text-amber-800 border-amber-300"
                                    )}>
                                      {holiday.reason || "Holiday"}
                                    </Badge>
                </div>
                                ))}
                                {upcomingHolidays.length > 3 && (
                                  <p className="text-xs text-amber-600 text-center">
                                    +{upcomingHolidays.length - 3} more in the next 7 days
                                  </p>
                                )}
                              </div>
                            );
                          }
                          
                          return (
                            <div className="text-center p-2 border border-dashed border-amber-300 rounded">
                              <p className="text-xs text-amber-700">
                                No holidays or off days scheduled for tomorrow.
                              </p>
                              <p className="text-xs text-amber-600 mt-1">
                                You'll receive automatic emails when holidays or off days are coming up.
                              </p>
                            </div>
                          );
                        })()}
                      </div>
              </div>
                  )}
                  
                  {/* Email Notifications Section */}
                  <div className="mt-6">
                    <Label className="text-base font-medium">Email Notifications</Label>
                    <div className="mt-2 space-y-4">
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium">Daily Class Reminders</p>
                          <p className="text-xs text-muted-foreground">Get reminders about upcoming classes</p>
                        </div>
                        <Button
                          size="sm"
                          variant={emailPreferences.attendanceReminders ? "default" : "outline"}
                          onClick={() => handleEmailPreferenceChange('attendanceReminders', !emailPreferences.attendanceReminders)}
                        >
                          {emailPreferences.attendanceReminders ? "Enabled" : "Enable"}
                        </Button>
                      </div>

                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium">Break Notifications</p>
                          <p className="text-xs text-muted-foreground">Receive alerts before breaks</p>
                        </div>
                        <Button
                          size="sm"
                          variant={emailPreferences.breakReminders ? "default" : "outline"}
                          onClick={() => handleEmailPreferenceChange('breakReminders', !emailPreferences.breakReminders)}
                        >
                          {emailPreferences.breakReminders ? "Enabled" : "Enable"}
                        </Button>
                      </div>

                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium">Holiday Alerts</p>
                          <p className="text-xs text-muted-foreground">Get notified about upcoming holidays</p>
                        </div>
                        <Button
                          size="sm"
                          variant={emailPreferences.holidayAlerts ? "default" : "outline"}
                          onClick={() => handleEmailPreferenceChange('holidayAlerts', !emailPreferences.holidayAlerts)}
                        >
                          {emailPreferences.holidayAlerts ? "Enabled" : "Enable"}
                        </Button>
                      </div>

                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium">Low Attendance Alerts</p>
                          <p className="text-xs text-muted-foreground">Receive warnings when attendance is low</p>
                        </div>
                        <Button
                          size="sm"
                          variant={emailPreferences.lowAttendanceAlerts ? "default" : "outline"}
                          onClick={() => handleEmailPreferenceChange('lowAttendanceAlerts', !emailPreferences.lowAttendanceAlerts)}
                        >
                          {emailPreferences.lowAttendanceAlerts ? "Enabled" : "Enable"}
                        </Button>
                      </div>

                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium">Daily Summary</p>
                          <p className="text-xs text-muted-foreground">Get a daily summary of your attendance</p>
                        </div>
                        <Button
                          size="sm"
                          variant={emailPreferences.dailySummary ? "default" : "outline"}
                          onClick={() => handleEmailPreferenceChange('dailySummary', !emailPreferences.dailySummary)}
                        >
                          {emailPreferences.dailySummary ? "Enabled" : "Enable"}
                        </Button>
                      </div>

                      <div className="pt-4 border-t">
                        <div className="flex items-center gap-2">
                          <Input
                            type="email"
                            placeholder="Enter your email address"
                            value={userEmail}
                            onChange={(e) => setUserEmail(e.target.value)}
                            className="flex-1"
                          />
                          <Button
                            onClick={() => {
                              saveToLocalStorage('user_email', userEmail);
                              toast({
                                title: "Email Saved",
                                description: "Your email has been saved for notifications.",
                              });
                            }}
                            disabled={!userEmail || !userEmail.includes('@')}
                          >
                            Save Email
                          </Button>
                        </div>
                        <p className="text-xs text-muted-foreground mt-2">
                          Enter your email address to receive notifications
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Notes */}
                  <div className="mt-6">
                    <Label htmlFor="notes" className="text-base font-medium">Notes (Optional)</Label>
                    <Textarea
                      id="notes"
                      value={notes}
                      onChange={(e) => setNotes(e.target.value)}
                      placeholder="Add any notes about today's classes"
                      className="mt-2"
                      rows={3}
                    />
                  </div>
                </>
            )}
          </CardContent>
        </Card>
      </div>
      </TooltipProvider>
    </div>
  );
} 