"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { getFromLocalStorage } from "@/lib/storage-utils"
import { format, parseISO } from "date-fns"
import { Check, Filter, Calendar } from "lucide-react"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

interface AttendanceRecord {
  id: string;
  date: string;
  subject: string;
  classId?: string;
  className?: string;
  subjectName?: string;
  status: "present" | "absent";
  classType?: string;
  time?: string;
  room?: string;
  autoMarked?: boolean;
  isAutoGenerated?: boolean;
  notes?: string;
}

interface ClassAttendanceData {
  name: string;
  totalAutoMarked: number;
  records: AttendanceRecord[];
}

export function AutoMarkedAttendance() {
  const [isLoading, setIsLoading] = useState(true);
  const [attendanceData, setAttendanceData] = useState<ClassAttendanceData[]>([]);
  const [filterTab, setFilterTab] = useState<"all" | "recent" | "class" | "today">("all");
  const [totalAutoMarked, setTotalAutoMarked] = useState(0);
  const [todayAutoMarked, setTodayAutoMarked] = useState<AttendanceRecord[]>([]);
  const [stats, setStats] = useState({
    totalClasses: 0,
    endOfDayAuto: 0,
    systemAuto: 0
  });

  useEffect(() => {
    // Fetch all attendance records
    const records = getFromLocalStorage<AttendanceRecord[]>("attendance_records", []);
    
    // Filter to only include auto-marked present records
    const autoMarkedRecords = records.filter(
      record => (record.autoMarked === true || record.isAutoGenerated === true) && record.status === "present"
    );
    
    setTotalAutoMarked(autoMarkedRecords.length);
    
    // Calculate statistics
    const endOfDay = autoMarkedRecords.filter(r => 
      r.notes?.toLowerCase().includes("end of day") || 
      r.notes?.toLowerCase().includes("automatically marked")
    ).length;
    
    const system = autoMarkedRecords.length - endOfDay;
    
    setStats({
      totalClasses: autoMarkedRecords.length,
      endOfDayAuto: endOfDay,
      systemAuto: system
    });
    
    // Check for today's auto-marked classes
    const today = new Date().toISOString().split('T')[0];
    const todayRecords = autoMarkedRecords.filter(r => r.date.startsWith(today));
    setTodayAutoMarked(todayRecords);
    
    // Group records by class/subject name
    const classGroups: Record<string, AttendanceRecord[]> = {};
    
    autoMarkedRecords.forEach(record => {
      // Determine the class name from various possible fields
      const className = record.className || record.subjectName || record.subject || "Unknown Class";
      
      if (!classGroups[className]) {
        classGroups[className] = [];
      }
      
      classGroups[className].push(record);
    });
    
    // Sort records within each class by date (newest first)
    Object.values(classGroups).forEach(records => {
      records.sort((a, b) => {
        // Convert strings to Date objects for comparison
        return new Date(b.date).getTime() - new Date(a.date).getTime();
      });
    });
    
    // Convert to array format for rendering
    const groupedData: ClassAttendanceData[] = Object.entries(classGroups).map(([name, records]) => ({
      name,
      totalAutoMarked: records.length,
      records
    }));
    
    // Sort classes by number of auto-marked attendances (highest first)
    groupedData.sort((a, b) => b.totalAutoMarked - a.totalAutoMarked);
    
    setAttendanceData(groupedData);
    setIsLoading(false);
  }, []);

  // Get records from the last 7 days
  const recentAutoMarkedRecords = () => {
    const allRecords = attendanceData.flatMap(data => data.records);
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    
    return allRecords
      .filter(record => new Date(record.date) >= sevenDaysAgo)
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  };

  // Format date for display
  const formatDate = (dateString: string) => {
    try {
      const date = parseISO(dateString);
      return format(date, "EEE, MMMM d, yyyy");
    } catch (error) {
      return dateString;
    }
  };

  // Get reason for auto-marking
  const getAutoMarkReason = (record: AttendanceRecord) => {
    if (record.notes) {
      if (record.notes.toLowerCase().includes("end of day")) {
        return "End of day auto-marking";
      }
      if (record.notes.toLowerCase().includes("automatically marked")) {
        return "Auto-marked (past class)";
      }
    }
    return "System auto-marked";
  };

  // Get badge color based on auto-mark reason
  const getAutoMarkBadgeClass = (record: AttendanceRecord) => {
    if (record.notes) {
      if (record.notes.toLowerCase().includes("end of day")) {
        return "bg-blue-100 text-blue-800 border-blue-300";
      }
      if (record.notes.toLowerCase().includes("automatically marked")) {
        return "bg-green-100 text-green-800 border-green-300";
      }
    }
    return "bg-purple-100 text-purple-800 border-purple-300";
  };

  if (isLoading) {
    return (
      <Card className="shadow-lg">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-medium flex items-center gap-2">
            <Check className="h-5 w-5 text-primary" />
            <span>Auto-Marked Attendance</span>
          </CardTitle>
          <CardDescription>Classes automatically marked as present</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="shadow-lg hover:shadow-xl transition-all duration-300">
      <CardHeader className="pb-2">
        <div className="flex justify-between items-start">
          <div>
            <CardTitle className="text-lg font-medium flex items-center gap-2">
              <Check className="h-5 w-5 text-primary" />
              <span>Auto-Marked Attendance</span>
            </CardTitle>
            <CardDescription>Classes automatically marked as present</CardDescription>
          </div>
          <Badge variant="outline" className="flex items-center gap-1">
            <Check className="h-3 w-3 text-green-500" />
            <span>{totalAutoMarked} auto-marked</span>
          </Badge>
        </div>
        
        <div className="grid grid-cols-3 gap-2 mt-3">
          <div className="border rounded-md p-2 bg-blue-50">
            <p className="text-xs text-muted-foreground">Total Auto-marked</p>
            <p className="text-lg font-semibold">{stats.totalClasses}</p>
          </div>
          <div className="border rounded-md p-2 bg-green-50">
            <p className="text-xs text-muted-foreground">End of Day Auto</p>
            <p className="text-lg font-semibold">{stats.endOfDayAuto}</p>
          </div>
          <div className="border rounded-md p-2 bg-purple-50">
            <p className="text-xs text-muted-foreground">System Auto</p>
            <p className="text-lg font-semibold">{stats.systemAuto}</p>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="all" className="space-y-4" onValueChange={(value) => setFilterTab(value as any)}>
          <TabsList className="grid grid-cols-4 w-full">
            <TabsTrigger value="all">All Classes</TabsTrigger>
            <TabsTrigger value="today">
              Today
              {todayAutoMarked.length > 0 && (
                <Badge className="ml-2 bg-primary text-primary-foreground">{todayAutoMarked.length}</Badge>
              )}
            </TabsTrigger>
            <TabsTrigger value="recent">Last 7 Days</TabsTrigger>
            <TabsTrigger value="class">By Class</TabsTrigger>
          </TabsList>
          
          <TabsContent value="today" className="space-y-4">
            {todayAutoMarked.length > 0 ? (
              todayAutoMarked.map(record => (
                <div key={record.id} className="p-3 border rounded-md hover:bg-accent/5 transition-colors border-l-4 border-l-blue-400">
                  <div className="flex justify-between items-start mb-1">
                    <div className="font-medium">{record.className || record.subjectName || record.subject}</div>
                    <Badge 
                      variant="outline" 
                      className={getAutoMarkBadgeClass(record)}
                    >
                      {getAutoMarkReason(record)}
                    </Badge>
                  </div>
                  <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>{formatDate(record.date)}</span>
                    {record.classType && (
                      <Badge variant="outline" className="text-xs">
                        {record.classType}
                      </Badge>
                    )}
                    {record.time && (
                      <span className="text-xs bg-primary/10 px-1.5 py-0.5 rounded">{record.time}</span>
                    )}
                    {record.room && (
                      <span className="text-xs bg-accent/20 px-1.5 py-0.5 rounded">{record.room}</span>
                    )}
                  </div>
                  {record.notes && (
                    <p className="text-xs text-muted-foreground mt-1">{record.notes}</p>
                  )}
                </div>
              ))
            ) : (
              <div className="text-center py-8 text-muted-foreground">
                <p>No auto-marked attendance for today</p>
              </div>
            )}
          </TabsContent>
          
          <TabsContent value="all" className="space-y-4">
            {attendanceData.flatMap(data => data.records)
              .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
              .map(record => (
                <div key={record.id} className="p-3 border rounded-md hover:bg-accent/5 transition-colors">
                  <div className="flex justify-between items-start mb-1">
                    <div className="font-medium">{record.className || record.subjectName || record.subject}</div>
                    <Badge 
                      variant="outline" 
                      className={getAutoMarkBadgeClass(record)}
                    >
                      {getAutoMarkReason(record)}
                    </Badge>
                  </div>
                  <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>{formatDate(record.date)}</span>
                    {record.classType && (
                      <Badge variant="outline" className="text-xs">
                        {record.classType}
                      </Badge>
                    )}
                    {record.time && (
                      <span className="text-xs bg-primary/10 px-1.5 py-0.5 rounded">{record.time}</span>
                    )}
                    {record.room && (
                      <span className="text-xs bg-accent/20 px-1.5 py-0.5 rounded">{record.room}</span>
                    )}
                  </div>
                  {record.notes && (
                    <p className="text-xs text-muted-foreground mt-1">{record.notes}</p>
                  )}
                </div>
              ))}
          </TabsContent>
          
          <TabsContent value="recent" className="space-y-4">
            {recentAutoMarkedRecords().length > 0 ? (
              recentAutoMarkedRecords().map(record => (
                <div key={record.id} className="p-3 border rounded-md hover:bg-accent/5 transition-colors">
                  <div className="flex justify-between items-start mb-1">
                    <div className="font-medium">{record.className || record.subjectName || record.subject}</div>
                    <Badge 
                      variant="outline" 
                      className={getAutoMarkBadgeClass(record)}
                    >
                      {getAutoMarkReason(record)}
                    </Badge>
                  </div>
                  <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
                    <Calendar className="h-3.5 w-3.5" />
                    <span>{formatDate(record.date)}</span>
                    {record.classType && (
                      <Badge variant="outline" className="text-xs">
                        {record.classType}
                      </Badge>
                    )}
                    {record.time && (
                      <span className="text-xs bg-primary/10 px-1.5 py-0.5 rounded">{record.time}</span>
                    )}
                    {record.room && (
                      <span className="text-xs bg-accent/20 px-1.5 py-0.5 rounded">{record.room}</span>
                    )}
                  </div>
                  {record.notes && (
                    <p className="text-xs text-muted-foreground mt-1">{record.notes}</p>
                  )}
                </div>
              ))
            ) : (
              <div className="text-center py-8 text-muted-foreground">
                <p>No auto-marked attendance in the last 7 days</p>
              </div>
            )}
          </TabsContent>
          
          <TabsContent value="class" className="space-y-4">
            <Accordion type="single" collapsible className="w-full">
              {attendanceData.map((classData, index) => (
                <AccordionItem key={index} value={`class-${index}`}>
                  <AccordionTrigger className="hover:bg-accent/5 px-3 py-2 rounded-md">
                    <div className="flex justify-between items-center w-full text-left">
                      <span className="font-medium">{classData.name}</span>
                      <Badge variant="secondary" className="ml-2">
                        {classData.totalAutoMarked}
                      </Badge>
                    </div>
                  </AccordionTrigger>
                  <AccordionContent className="pl-6 pr-2">
                    <div className="space-y-2 mt-1">
                      {classData.records.map(record => (
                        <div key={record.id} className="p-2 border rounded-md text-sm hover:bg-accent/5">
                          <div className="flex justify-between items-center mb-1">
                            <div className="flex items-center gap-2">
                              <Calendar className="h-3.5 w-3.5 text-muted-foreground" />
                              <span>{formatDate(record.date)}</span>
                            </div>
                            <Badge 
                              variant="outline" 
                              className={`text-xs ${getAutoMarkBadgeClass(record)}`}
                            >
                              {getAutoMarkReason(record)}
                            </Badge>
                          </div>
                          <div className="flex flex-wrap gap-2 mt-1 text-xs">
                            {record.time && (
                              <span className="bg-primary/10 px-1.5 py-0.5 rounded">{record.time}</span>
                            )}
                            {record.room && (
                              <span className="bg-accent/20 px-1.5 py-0.5 rounded">{record.room}</span>
                            )}
                            {record.classType && (
                              <Badge variant="outline" className="text-xs">
                                {record.classType}
                              </Badge>
                            )}
                          </div>
                          {record.notes && (
                            <p className="text-xs text-muted-foreground mt-1">{record.notes}</p>
                          )}
                        </div>
                      ))}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
} 