"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { CalendarDays, Clock, MapPin, CheckCircle, XCircle } from "lucide-react"
import { getFromLocalStorage } from "@/lib/storage-utils"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { isBreakClass } from "@/lib/attendance-utils"

interface AttendanceRecord {
  id: string;
  date: string;
  classId?: string;
  className?: string;
  subjectName?: string;
  status: "present" | "absent";
  classType?: string;
  time?: string;
  room?: string;
  autoMarked?: boolean;
  notes?: string;
  isAutoGenerated?: boolean;
}

interface ClassEntry {
  id: string;
  day: string;
  name: string;
  subject?: string;
  time?: string;
  startTime?: string;
  endTime?: string;
  room: string;
  classType?: string;
  fromPdf?: boolean;
}

interface ClassAttendanceStats {
  id: string;
  name: string;
  day: string;
  time: string;
  room: string;
  classType: string;
  total: number;
  present: number;
  absent: number;
  percentage: number;
}

export function ClassAttendanceBreakdown() {
  const [isLoading, setIsLoading] = useState(true);
  const [classAttendance, setClassAttendance] = useState<ClassAttendanceStats[]>([]);

  useEffect(() => {
    // Fetch attendance data and schedule
    const attendanceRecords = getFromLocalStorage<AttendanceRecord[]>('attendance_records', []);
    const schedule = getFromLocalStorage<{classes: ClassEntry[]}>('schedule', {classes: []});
    
    if (!schedule.classes || schedule.classes.length === 0) {
      setIsLoading(false);
      return;
    }
    
    // Filter out break classes
    const filteredClasses = schedule.classes.filter(classItem => !isBreakClass(classItem));
    
    // Prepare class-specific attendance data
    const classStats: ClassAttendanceStats[] = filteredClasses.map(classItem => {
      // Prioritize different name fields that could be present
      const className = classItem.name || classItem.subject || "Unknown Class";
      const classId = classItem.id;
      const day = classItem.day;
      const time = classItem.time || 
                  (classItem.startTime && classItem.endTime 
                    ? `${classItem.startTime} - ${classItem.endTime}`
                    : "Unknown time");
      const room = classItem.room || "Unknown room";
      const classType = classItem.classType || "Lecture";
      
      // Find all records for this specific class
      const classRecords = attendanceRecords.filter(record => {
        try {
          // Direct class ID match is most reliable when available
          if (record.classId && classId) {
            return record.classId === classId;
          }
          
          // If no direct class ID match, try name matching
          let nameMatch = false;
          if (record.className || record.subjectName) {
            const recordName = record.className || record.subjectName || "";
            nameMatch = recordName.toLowerCase() === className.toLowerCase();
          }
          
          // Check if this is the right day of the week
          const recordDate = new Date(record.date);
          const recordDay = recordDate.toLocaleDateString("en-US", { weekday: "long" });
          const dayMatch = recordDay === day;
          
          // Consider time when available
          let timeMatch = true;
          if (record.time && time !== "Unknown time") {
            timeMatch = record.time.toLowerCase() === time.toLowerCase();
          }
          
          // Consider room when available
          let roomMatch = true;
          if (record.room && room !== "Unknown room") {
            roomMatch = record.room.toLowerCase() === room.toLowerCase();
          }
          
          // Consider class type when available
          let typeMatch = true;
          if (record.classType && classType !== "Lecture") {
            typeMatch = record.classType.toLowerCase() === classType.toLowerCase();
          }
          
          return nameMatch && dayMatch && timeMatch && roomMatch && typeMatch;
        } catch (error) {
          console.error("Error processing attendance record:", error, record);
          return false; // Skip problematic records
        }
      });
      
      // Calculate stats
      const total = classRecords.length;
      const present = classRecords.filter(r => r.status === 'present').length;
      const absent = classRecords.filter(r => r.status === 'absent').length;
      const percentage = total > 0 ? Math.round((present / total) * 100) : 0;
      
      return {
        id: classId,
        name: className,
        day,
        time,
        room,
        classType,
        total,
        present,
        absent,
        percentage
      };
    });
    
    // Sort by day and time
    const daysOrder = {
      "Monday": 1,
      "Tuesday": 2,
      "Wednesday": 3,
      "Thursday": 4,
      "Friday": 5,
      "Saturday": 6,
      "Sunday": 7
    };
    
    classStats.sort((a, b) => {
      // First by day of week
      const dayA = a.day as keyof typeof daysOrder;
      const dayB = b.day as keyof typeof daysOrder;
      
      const dayOrder = daysOrder[dayA] - daysOrder[dayB];
      if (dayOrder !== 0) return dayOrder;
      
      // Then by time
      const timeA = a.time || "";
      const timeB = b.time || "";
      return timeA.localeCompare(timeB);
    });
    
    setClassAttendance(classStats);
    setIsLoading(false);
  }, []);

  if (isLoading) {
    return (
      <Card className="shadow-lg">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-medium flex items-center gap-2">
            <CalendarDays className="h-5 w-5 text-primary" />
            <span>Class-by-Class Attendance</span>
          </CardTitle>
          <CardDescription>Your attendance breakdown for individual class sessions</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (classAttendance.length === 0) {
    return (
      <Card className="shadow-lg">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-medium flex items-center gap-2">
            <CalendarDays className="h-5 w-5 text-primary" />
            <span>Class-by-Class Attendance</span>
          </CardTitle>
          <CardDescription>Your attendance breakdown for individual class sessions</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8 text-muted-foreground">
            <p>No class attendance data available. Start tracking your attendance to see statistics for each class.</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="shadow-lg hover:shadow-xl transition-all duration-300">
      <CardHeader className="pb-2">
        <CardTitle className="text-lg font-medium flex items-center gap-2">
          <CalendarDays className="h-5 w-5 text-primary" />
          <span>Class-by-Class Attendance</span>
        </CardTitle>
        <CardDescription>Your attendance breakdown for individual class sessions</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {classAttendance.map((classData, index) => (
            <div key={`${classData.id}-${index}`} className="border rounded-md p-4 hover:bg-accent/5 transition-colors">
              <div className="flex flex-col space-y-3">
                {/* Class header */}
                <div className="flex justify-between items-start">
                  <div>
                    <h4 className="font-medium text-sm uppercase">{classData.name}</h4>
                    <div className="flex flex-wrap items-center gap-2 mt-1 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <CalendarDays className="h-3 w-3" /> {classData.day}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3" /> {classData.time}
                      </span>
                      <span className="flex items-center gap-1">
                        <MapPin className="h-3 w-3" /> {classData.room}
                      </span>
                    </div>
                  </div>
                  <Badge variant="outline" className="capitalize">
                    {classData.classType}
                  </Badge>
                </div>
                
                {/* Attendance progress */}
                <div className="space-y-1">
                  <div className="flex justify-between items-center text-xs text-muted-foreground">
                    <span>Attendance: {classData.percentage}%</span>
                    <span>{classData.present}/{classData.total} classes</span>
                  </div>
                  <Progress 
                    value={classData.percentage} 
                    className={`h-2 ${
                      classData.percentage >= 90 ? "bg-green-100" : 
                      classData.percentage >= 75 ? "bg-yellow-100" : 
                      "bg-red-100"
                    }`} 
                  />
                </div>
                
                {/* Stats */}
                <div className="grid grid-cols-2 gap-2 mt-2">
                  <div className="flex items-center gap-2 rounded-md bg-green-50 p-2">
                    <CheckCircle className="h-4 w-4 text-green-500" />
                    <div>
                      <p className="text-xs font-medium">Present</p>
                      <p className="text-lg font-bold text-green-700">{classData.present}</p>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-2 rounded-md bg-red-50 p-2">
                    <XCircle className="h-4 w-4 text-red-500" />
                    <div>
                      <p className="text-xs font-medium">Absent</p>
                      <p className="text-lg font-bold text-red-700">{classData.absent}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
} 