"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { CalendarDays, BookOpen, Beaker, Video, PencilRuler, Calculator } from "lucide-react"
import { getFromLocalStorage } from "@/lib/storage-utils"
import { Badge } from "@/components/ui/badge"
import { isBreakClass, calculateAttendanceExcludingHolidays, calculateSubjectAttendanceExcludingHolidays } from "@/lib/attendance-utils"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"

interface AttendanceRecord {
  id: string;
  date: string;
  classId: string;
  className: string;
  status: "present" | "absent";
  classType?: string;
  time?: string;
  room?: string;
  autoMarked?: boolean;
  notes?: string;
  isAutoGenerated?: boolean;
}

interface ClassEntry {
  id: string;
  day: string;
  name: string;
  subject?: string;
  time?: string;
  startTime?: string;
  endTime?: string;
  room: string;
  classType?: string;
  fromPdf?: boolean;
}

interface ClassAttendanceStats {
  id: string;
  name: string;
  day: string;
  time: string;
  room: string;
  classType: string;
  total: number;
  present: number;
  absent: number;
  percentage: number;
}

// Define a type for the grouped class data
type GroupedClassData = {
  name: string;
  classType: string;
  total: number;
  present: number;
  absent: number;
  percentage: number;
  day?: string;
  time?: string;
  room?: string;
};

export function ClassSpecificAttendance() {
  const [isLoading, setIsLoading] = useState(true);
  const [classAttendance, setClassAttendance] = useState<ClassAttendanceStats[]>([]);
  const [activeTab, setActiveTab] = useState("byClass");
  const [globalStats, setGlobalStats] = useState({
    total: 0,
    present: 0,
    absent: 0,
    percentage: 0
  });
  const [classStats, setClassStats] = useState<Record<string, { 
    total: number; 
    present: number; 
    absent: number; 
    percentage: number;
    name: string;
    type: string;
  }>>({});

  // Get icon based on class type
  const getClassTypeIcon = (classType: string) => {
    const type = classType.toLowerCase();
    if (type.includes('lecture')) return <BookOpen className="h-4 w-4" />;
    if (type.includes('lab')) return <Beaker className="h-4 w-4" />;
    if (type.includes('tutorial')) return <Video className="h-4 w-4" />;
    if (type.includes('practical')) return <PencilRuler className="h-4 w-4" />;
    return <Calculator className="h-4 w-4" />;
  };

  // Helper to get status color
  const getStatusColor = (percentage: number) => {
    if (percentage >= 90) return "bg-green-500";
    if (percentage >= 75) return "bg-yellow-500";
    return "bg-red-500";
  };

  useEffect(() => {
    // Fetch attendance data and schedule
    const attendanceRecords = getFromLocalStorage<any[]>('attendance_records', []);
    const schedule = getFromLocalStorage<{classes: ClassEntry[]}>('schedule', {classes: []});
    
    // Get accurate overall attendance data
    const accurateStats = calculateAttendanceExcludingHolidays(attendanceRecords);
    setGlobalStats(accurateStats);
    
    // Get accurate class-specific attendance data
    const classes = schedule.classes || [];
    const subjectStats = calculateSubjectAttendanceExcludingHolidays(attendanceRecords, classes);
    
    // Add type property to each class stat
    const accurateClassStats: Record<string, { 
      total: number; 
      present: number; 
      absent: number; 
      percentage: number;
      name: string;
      type: string;
    }> = {};
    
    Object.entries(subjectStats).forEach(([id, stats]) => {
      // Find the class in schedule to get its type
      const classEntry = classes.find(c => c.id === id);
      accurateClassStats[id] = {
        ...stats,
        type: classEntry?.classType || "Lecture" // Default to "Lecture" if type not found
      };
    });
    
    setClassStats(accurateClassStats);
    
    if (!schedule.classes || schedule.classes.length === 0) {
      setIsLoading(false);
      return;
    }
    
    // Filter out break classes
    const filteredClasses = schedule.classes.filter(classItem => !isBreakClass(classItem));
    
    // Prepare class-specific attendance data
    const classAttendanceStats: ClassAttendanceStats[] = [];
    
    filteredClasses.forEach(classItem => {
      // Prioritize different name fields that could be present
      const className = classItem.name || classItem.subject || "Unknown Class";
      const classId = classItem.id;
      const day = classItem.day;
      const time = classItem.time || 
                  (classItem.startTime && classItem.endTime 
                    ? `${classItem.startTime} - ${classItem.endTime}`
                    : "Unknown time");
      const room = classItem.room || "Unknown room";
      const classType = classItem.classType || "Lecture";
      
      // Find all records for this specific class using our utility functions
      // First try to find the matching class in our accurate class stats
      const matchingClass = accurateClassStats[classId];
      
      let total = 0;
      let present = 0;
      let absent = 0;
      let percentage = 0;
      
      if (matchingClass) {
        // If we found a match in accurate stats, use those numbers
        total = matchingClass.total;
        present = matchingClass.present;
        absent = matchingClass.absent;
        percentage = matchingClass.percentage;
      } else {
        // If no match in class stats, find records specifically for this class
        const classRecords = attendanceRecords.filter(record => {
          if (!record) return false;
          
          // Direct class ID match is most reliable when available
          if (record.classId) {
            return record.classId === classId;
          }
          
          // Safely extract the class name
          const recordName = record.className || record.subjectName || "";
          const nameMatch = recordName.toLowerCase() === className.toLowerCase();
          
          // Check if this is the right day of the week
          let dayMatch = false;
          try {
            const recordDate = new Date(record.date);
            const recordDay = recordDate.toLocaleDateString("en-US", { weekday: "long" });
            dayMatch = recordDay === day;
          } catch (e) {
            console.error("Error parsing date:", e);
          }
          
          // Check time match if available
          let timeMatch = true;
          if (record.time && time !== "Unknown time") {
            timeMatch = record.time.toLowerCase() === time.toLowerCase();
          }
          
          // Check room match if available
          let roomMatch = true;
          if (record.room && room !== "Unknown room") {
            roomMatch = record.room.toLowerCase() === room.toLowerCase();
          }
          
          // Check class type match if available
          let typeMatch = true;
          if (record.classType && classType !== "Lecture") {
            typeMatch = record.classType.toLowerCase() === classType.toLowerCase();
          }
          
          // Use the combination of attributes
          return nameMatch && dayMatch && timeMatch && roomMatch && typeMatch;
        });
        
        // Calculate stats from records
        total = classRecords.length;
        present = classRecords.filter(r => r && r.status === 'present').length;
        absent = classRecords.filter(r => r && r.status === 'absent').length;
        percentage = total > 0 ? Math.round((present / total) * 100) : 0;
      }
      
      classAttendanceStats.push({
        id: classId,
        name: className,
        day,
        time,
        room,
        classType,
        total,
        present,
        absent,
        percentage
      });
    });
    
    // Sort by day and time
    const daysOrder = {
      "Monday": 1,
      "Tuesday": 2,
      "Wednesday": 3,
      "Thursday": 4,
      "Friday": 5,
      "Saturday": 6,
      "Sunday": 7
    };
    
    classAttendanceStats.sort((a, b) => {
      // First by day of week
      const dayA = a.day as keyof typeof daysOrder;
      const dayB = b.day as keyof typeof daysOrder;
      
      const dayOrder = (daysOrder[dayA] || 0) - (daysOrder[dayB] || 0);
      if (dayOrder !== 0) return dayOrder;
      
      // Then by time
      const timeA = a.time || "";
      const timeB = b.time || "";
      return timeA.localeCompare(timeB);
    });
    
    setClassAttendance(classAttendanceStats);
    setIsLoading(false);
  }, []);

  // Group classes by class type
  const classesByType = classAttendance.reduce<Record<string, ClassAttendanceStats[]>>((acc, classData) => {
    const type = classData.classType || "Other";
    if (!acc[type]) {
      acc[type] = [];
    }
    acc[type].push(classData);
    return acc;
  }, {});

  if (isLoading) {
    return (
      <Card className="shadow-lg">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-medium flex items-center gap-2">
            <CalendarDays className="h-5 w-5 text-primary" />
            <span>Class Attendance</span>
          </CardTitle>
          <CardDescription>Attendance by class</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (classAttendance.length === 0) {
    return (
      <Card className="shadow-lg">
        <CardHeader className="pb-2">
          <CardTitle className="text-lg font-medium flex items-center gap-2">
            <CalendarDays className="h-5 w-5 text-primary" />
            <span>Class Attendance</span>
          </CardTitle>
          <CardDescription>Attendance by class</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8 text-muted-foreground">
            <p>No class attendance data available. Start tracking your attendance to see statistics for each class.</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="shadow-lg hover:shadow-xl transition-all duration-300">
      <CardHeader className="pb-2">
        <CardTitle className="text-lg font-medium flex items-center gap-2">
          <CalendarDays className="h-5 w-5 text-primary" />
          <span>Class Attendance</span>
        </CardTitle>
        <CardDescription>Attendance by class</CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="byClass" className="space-y-4" onValueChange={setActiveTab}>
          <TabsList>
            <TabsTrigger value="byClass">By Class</TabsTrigger>
            <TabsTrigger value="byType">By Type</TabsTrigger>
          </TabsList>

          <TabsContent value="byClass" className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
              {/* Group by class name and type to avoid duplicates */}
              {Object.entries(
                classAttendance.reduce<Record<string, GroupedClassData>>((acc, classData) => {
                  // Normalize class name and type to avoid duplication due to case/spacing differences
                  const normalizedName = classData.name.trim().toLowerCase();
                  const normalizedType = classData.classType.trim().toLowerCase();
                  const key = `${normalizedName}-${normalizedType}`;
                  
                  if (!acc[key]) {
                    acc[key] = { 
                      name: classData.name, // Keep original name for display
                      classType: classData.classType, // Keep original type for display
                      total: classData.total,
                      present: classData.present,
                      absent: classData.absent,
                      percentage: classData.percentage
                    };
                  } else {
                    // Combine stats for the same class name + type
                    acc[key].total += classData.total;
                    acc[key].present += classData.present;
                    acc[key].absent += classData.absent;
                    // Recalculate percentage
                    acc[key].percentage = acc[key].total > 0 
                      ? Math.round((acc[key].present / acc[key].total) * 100) 
                      : 0;
                  }
                  return acc;
                }, {})
              ).map(([key, classData]) => (
                <div key={key} className="border rounded-md p-2 hover:bg-accent/5 transition-colors">
                  <div className="flex flex-col">
                    {/* Header with name and type */}
                    <div className="flex justify-between items-center mb-1">
                      <h4 className="font-medium text-sm uppercase truncate">{classData.name}</h4>
                      <Badge variant="outline" className="text-xs">
                        {classData.classType}
                      </Badge>
                    </div>
                    
                    {/* Simple progress bar */}
                    <div className="w-full bg-gray-100 h-1.5 rounded-full mb-2">
                      <div 
                        className={`h-full rounded-full ${getStatusColor(classData.percentage)}`}
                        style={{ width: `${classData.percentage}%` }}
                      ></div>
                    </div>
                    
                    {/* Compact attendance stats */}
                    <div className="flex justify-between items-center text-xs">
                      <span className="font-medium">{classData.percentage}%</span>
                      <div>
                        <span className="text-green-600">{classData.present}</span>
                        <span className="mx-0.5">/</span>
                        <span className="text-red-600">{classData.absent}</span>
                        <span className="mx-0.5">/</span>
                        <span>{classData.total}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="byType" className="space-y-6">
            {Object.entries(classesByType).map(([classType, classes]) => {
              // Group classes by name within each type
              const groupedByName = classes.reduce<Record<string, GroupedClassData>>((acc, classData) => {
                const normalizedName = classData.name.trim().toLowerCase();
                const key = normalizedName;
                
                if (!acc[key]) {
                  acc[key] = { 
                    name: classData.name,
                    classType: classData.classType,
                    total: classData.total,
                    present: classData.present,
                    absent: classData.absent,
                    percentage: classData.percentage
                  };
                } else {
                  // Combine stats for the same class name within this type
                  acc[key].total += classData.total;
                  acc[key].present += classData.present;
                  acc[key].absent += classData.absent;
                  // Recalculate percentage
                  acc[key].percentage = acc[key].total > 0 
                    ? Math.round((acc[key].present / acc[key].total) * 100) 
                    : 0;
                }
                return acc;
              }, {});

              return (
                <div key={classType} className="space-y-3">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="bg-primary/10 p-1.5 rounded-full">
                      {getClassTypeIcon(classType)}
                    </div>
                    <h3 className="text-sm font-semibold">{classType} Classes</h3>
                  </div>
                  
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                    {Object.entries(groupedByName).map(([key, classData]) => (
                      <div key={`${classType}-${key}`} className="border rounded-md p-2 hover:bg-accent/5 transition-colors">
                        <div className="flex flex-col">
                          {/* Header with just the name since type is in the section header */}
                          <div className="flex justify-between items-center mb-1">
                            <h4 className="font-medium text-sm uppercase truncate">{classData.name}</h4>
                            <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${
                              classData.percentage >= 90 ? "bg-green-100 text-green-800" : 
                              classData.percentage >= 75 ? "bg-yellow-100 text-yellow-800" : 
                              "bg-red-100 text-red-800"
                            }`}>
                              {classData.percentage}%
                            </span>
                          </div>
                          
                          {/* Simple progress bar */}
                          <div className="w-full bg-gray-100 h-1.5 rounded-full mb-2">
                            <div 
                              className={`h-full rounded-full ${getStatusColor(classData.percentage)}`}
                              style={{ width: `${classData.percentage}%` }}
                            ></div>
                          </div>
                          
                          {/* Stats row with labels */}
                          <div className="grid grid-cols-3 gap-1 mt-1">
                            <div className="flex flex-col items-center text-xs">
                              <span className="text-muted-foreground">Present</span>
                              <span className="font-bold text-green-600">{classData.present}</span>
                            </div>
                            <div className="flex flex-col items-center text-xs">
                              <span className="text-muted-foreground">Absent</span>
                              <span className="font-bold text-red-600">{classData.absent}</span>
                            </div>
                            <div className="flex flex-col items-center text-xs">
                              <span className="text-muted-foreground">Total</span>
                              <span className="font-bold">{classData.total}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
} 