import { getFromLocalStorage } from "./storage-utils";

export function isHoliday(date: Date | string): boolean {
  const holidays = getFromLocalStorage<string[]>('holidays', []);
  const dateStr = typeof date === 'string' ? date : date.toISOString().split('T')[0];
  return holidays.includes(dateStr);
}

export function isOffDay(date: Date | string): boolean {
  const schedule = getFromLocalStorage<{classes: any[]}>('schedule', {classes: []});
  const dateObj = typeof date === 'string' ? new Date(date) : date;
  const dayOfWeek = dateObj.toLocaleDateString("en-US", { weekday: "long" });
  
  const classesForDay = schedule.classes.filter(item => 
    item.day === dayOfWeek && 
    (!item.classType || !item.classType.toLowerCase().includes('break'))
  );
  
  return classesForDay.length === 0;
}

export function generateAutoPresentRecords(): any[] {
  const records = getFromLocalStorage<any[]>('attendance_records', []);
  return records.filter(record => 
    record.isAutoGenerated === true || 
    (record.notes && typeof record.notes === 'string' && record.notes.includes('Automatically marked as present'))
  );
}
