import { getFromLocalStorage } from "./storage-utils";

// Check if a date is a holiday
export function isHoliday(date: Date | string): boolean {
  // Get list of holidays
  const holidays = getFromLocalStorage<string[]>('holidays', []);
  
  // Convert date to string format if it's a Date object
  const dateStr = typeof date === 'string' ? date : date.toISOString().split('T')[0];
  
  // Check if the date is in holidays list
  return holidays.includes(dateStr);
}

// Get all holidays
export function getAllHolidays(): string[] {
  return getFromLocalStorage<string[]>('holidays', []);
}

// Check if a class is a break period
export function isBreakClass(classItem: any): boolean {
  return classItem.classType && 
    typeof classItem.classType === 'string' && 
    classItem.classType.toLowerCase().includes('break');
}

// Check if a date has no scheduled classes (off day)
export function isOffDay(date: Date | string): boolean {
  // Get the schedule
  const schedule = getFromLocalStorage<{classes: any[]}>('schedule', {classes: []});
  
  // Convert date to day of week
  const dateObj = typeof date === 'string' ? new Date(date) : date;
  const dayOfWeek = dateObj.toLocaleDateString("en-US", { weekday: "long" });
  
  // Check if there are any classes scheduled for this day of week
  const classesForDay = schedule.classes.filter(item => 
    item.day === dayOfWeek && 
    (!item.classType || !item.classType.toLowerCase().includes('break'))
  );
  
  return classesForDay.length === 0;
}

// Generate auto-present records for past classes
export function generateAutoPresentRecords(): any[] {
  // Get all attendance records
  const records = getFromLocalStorage<any[]>('attendance_records', []);
  
  // Check for records that have been auto-generated
  const autoGeneratedRecords = records.filter(record => 
    record.isAutoGenerated === true || 
    (record.notes && 
     typeof record.notes === 'string' && 
     record.notes.includes('Automatically marked as present'))
  );
  
  return autoGeneratedRecords;
}

// Calculate attendance excluding holidays
export function calculateAttendanceExcludingHolidays(records: any[]): {
  total: number;
  present: number;
  absent: number;
  percentage: number;
} {
  const holidays = getAllHolidays();
  
  // Filter out records that fall on holidays
  const filteredRecords = records.filter(record => {
    const recordDate = record.date;
    return !holidays.includes(recordDate);
  });
  
  // Count total, present and absent
  const total = filteredRecords.length;
  const present = filteredRecords.filter(r => r.status === 'present').length;
  const absent = filteredRecords.filter(r => r.status === 'absent').length;
  
  // Calculate percentage
  const percentage = total > 0 ? Math.round((present / total) * 100) : 0;
  
  return {
    total,
    present,
    absent,
    percentage
  };
}

// Calculate subject-wise attendance excluding holidays
export function calculateSubjectAttendanceExcludingHolidays(
  records: any[],
  subjects: any[]
): Record<string, { 
  total: number; 
  present: number; 
  absent: number; 
  percentage: number;
  name: string;
}> {
  const holidays = getAllHolidays();
  
  // Filter out records that fall on holidays
  const filteredRecords = records.filter(record => {
    const recordDate = record.date;
    return !holidays.includes(recordDate);
  });
  
  // Create a map to store subject-wise attendance
  const subjectAttendance: Record<string, { 
    total: number; 
    present: number; 
    absent: number; 
    percentage: number;
    name: string;
  }> = {};
  
  // Initialize with all subjects
  subjects.forEach(subject => {
    subjectAttendance[subject.id] = {
      total: 0,
      present: 0,
      absent: 0,
      percentage: 0,
      name: subject.name
    };
  });
  
  // Count attendance for each subject
  filteredRecords.forEach(record => {
    if (!subjectAttendance[record.subjectId]) {
      // Create entry for subjects not initially in the list
      subjectAttendance[record.subjectId] = {
        total: 0,
        present: 0,
        absent: 0,
        percentage: 0,
        name: record.subjectName || 'Unknown Subject'
      };
    }
    
    const data = subjectAttendance[record.subjectId];
    data.total += 1;
    
    if (record.status === 'present') {
      data.present += 1;
    } else {
      data.absent += 1;
    }
    
    // Calculate percentage
    data.percentage = data.total > 0 ? Math.round((data.present / data.total) * 100) : 0;
  });
  
  return subjectAttendance;
}

// Calculate class attendance with auto-present records
export function calculateClassAttendanceWithAutoPresentRecords(
  classes: any[]
): Record<string, {
  name: string;
  type: string;
  total: number;
  present: number;
  absent: number;
  percentage: number;
}> {
  const records = getFromLocalStorage<any[]>('attendance_records', []);
  const holidays = getAllHolidays();
  
  // Filter out records on holidays
  const filteredRecords = records.filter(record => !holidays.includes(record.date));
  
  const classAttendance: Record<string, {
    name: string;
    type: string;
    total: number;
    present: number;
    absent: number;
    percentage: number;
  }> = {};
  
  // Initialize with all classes
  classes.forEach(classItem => {
    if (!isBreakClass(classItem)) {
      classAttendance[classItem.id] = {
        name: classItem.name || classItem.subject || 'Unknown',
        type: classItem.classType || 'Lecture',
        total: 0,
        present: 0,
        absent: 0,
        percentage: 0
      };
    }
  });
  
  // Count attendance from records
  filteredRecords.forEach(record => {
    const classId = record.classId;
    
    if (classAttendance[classId]) {
      classAttendance[classId].total += 1;
      if (record.status === 'present') {
        classAttendance[classId].present += 1;
      } else {
        classAttendance[classId].absent += 1;
      }
    }
  });
  
  // Calculate percentages
  Object.values(classAttendance).forEach(data => {
    data.percentage = data.total > 0 ? Math.round((data.present / data.total) * 100) : 0;
  });
  
  return classAttendance;
} 